### ISSUE TITLE
markdown: modify parser to change the size of an image

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#1007]
### Affected part of DeckDeckGo

- [X] Web Components

### Feature Description

Our [markdown](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/markdown)  can parse image sizes as following:

```
![](https://www.nmattia.com/images/autoupdate-notifications.jpg "=100px,20px")
![](https://www.nmattia.com/images/autoupdate-notifications.jpg "=100px")
```

I have run polls on  [Twitter](https://twitter.com/daviddalbusco/status/1327277786839572481) and [Dev](https://dev.to/daviddalbusco/what-would-be-your-favorite-option-to-change-the-size-of-an-image-in-markdown-4phg) and it seems that most of the voters would rather like an option in which it is possible to specify keywords such as `width` or `height`.

That's why the goal of the issue  is to modify the parser to support these.

One often suggested solution would be  the following:

```
![](img.jpg|width=100,height=20)
```

But I am not sure  it is possible to implement with  [Marked.js](https://marked.js.org/) which we are using. Alos somehow I think that `""` may  be mandatory therefore I  would suggest following  solution but I am  open to better idea.

```
![](img.jpg "width=100px,height=20px")
```

**Comment by grantlouisherman** [comment]
hey @peterpeterparker I can take a look at this if that works!

**Comment by peterpeterparker** [comment]
@grantlouisherman sure would be awesome 👍 let me know if you have any questions!

P.S.: just merged #1011 30 seconds, if you forked the project before it, you might need to sync your branch as I did some changes in the component in that branch.

**Comment by grantlouisherman** [comment]
hey @peterpeterparker so I wanted to ask you a qq. When I ran the markdown code locally and just put in "width=<WIDTH>px,height=<HEIGHT>px" it seemed to update the image properly. Maybe I'm misunderstanding, but I think the "enhancement" was to make the `width,height` syntax available for input and it seems to already do that. Let me know your thoughts! 👍

**Comment by peterpeterparker** [comment]
@grantlouisherman it already does? ok that would be pretty nice :) can you show me the markdown code you used for the test? the one  in which you  added "width=px,height=px"   ?

**Comment by grantlouisherman** [comment]
<img width="1157" alt="after" src="https://user-images.githubusercontent.com/5606705/99582809-9ecab600-29b0-11eb-98e6-c17fad12e07c.png">
<img width="1070" alt="markdown_edit" src="https://user-images.githubusercontent.com/5606705/99582810-9f634c80-29b0-11eb-896b-ed3bc22afb4f.png">
<img width="1203" alt="before" src="https://user-images.githubusercontent.com/5606705/99582811-9f634c80-29b0-11eb-951b-808321676b4e.png">

**Comment by grantlouisherman** [comment]
So @peterpeterparker I technically lied. The width seems to update but not the height. I assume that the `deck-deck-go` img has a height attribute? I think I just need to update that image worker function you have.

**Comment by peterpeterparker** [comment]
thx for the feedback @grantlouisherman, effetively my current regex seems to be to weak 😅 

yes exactly I think it would be cool to update the `changeImgCreation` function to detect `height` and `width` if passed as following:

![](img.jpg "width=100px,height=20px")

and apply these to the related css deckgo-lazy-img.

agree?

**Comment by grantlouisherman** [comment]
hey @peterpeterparker I opened a draft PR here: https://github.com/deckgo/deckdeckgo/pull/1017. Let me know your thoughts on the implementation.
