### ISSUE TITLE
site: add a "close" button to the menu

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#1047]
### Affected part of DeckDeckGo

- [X] Site

### Feature Description

Add a "close" to the menu of the [website](https://deckdeckgo.com) (see mockups).

### Use Case

Even though a click on  the backdrop closes it, it would be more user friendly to display such an  action

###  Getting started

The site is developed with Gatsby.

```
git clone https://github.com/deckgo/deckdeckgo
cd site
npm ci
npm run dev
```

### Screenshots

<img width="1002" alt="Capture d’écran 2021-01-09 à 13 15 40" src="https://user-images.githubusercontent.com/16886711/104091755-c5ee8700-527f-11eb-95ba-1d8d7ef685d2.png">
<img width="663" alt="Capture d’écran 2021-01-09 à 13 15 44" src="https://user-images.githubusercontent.com/16886711/104091756-c71fb400-527f-11eb-831b-2f5707c3e195.png">
i

**Comment by saideepesh000** [comment]
@peterpeterparker, hey can I work on this

**Comment by peterpeterparker** [comment]
@saideepesh000 for sure! that would be super, thx.

let  me know if you have any questions.

**Comment by saideepesh000** [comment]
Hey @peterpeterparker, is there any image/icon of that "X" icon or should I take a screenshot of that and extract that "X" from that.

**Comment by peterpeterparker** [comment]
you can use the icon which finds place in [site/static/assets/icons/ionicons/close.svg](https://github.com/deckgo/deckdeckgo/blob/master/site/static/assets/icons/ionicons/close.svg)
