### ISSUE TITLE
[Drag, Resize and Rotate] `drrDidChange` not firing correctly after re-opening modal

### ISSUE THREAD

**Issue by mariasiuvlad** [deckgo/deckdeckgo#1051]
### Affected part of DeckDeckGo

- [x ] Web Components (Drag, Resize and Rotate)

### Reproduction

Using Drag, Resize and Rotate web component in a React project together with `react-modal` results in improper handling of the `drrDidChange` event

Steps to reproduce:

1. Open modal containing ddr component
2. Close modal
3. Open modal again
4. Drag ddr component

### Expected Behavior

`drrDidChange` event fires when the mouse button is released and the component follows the mouse motion

### Actual Behavior

`drrDidChange` event fires immediately after clicking and the x and y attributes are set to 0

Note that this only happens after closing and opening the modal at least one time and only the first time the modal is opened.
I hope the video provides further clarification.

https://user-images.githubusercontent.com/16286957/104178471-0e8a7980-5413-11eb-8ef0-a943f3aebc4d.mov

Please let me know if any additional info would be helpful.

### Additional Details

<details>
  <summary>DDR Element React component</summary>
  
 ```
import React, { useEffect, useRef } from 'react';
import { ALIGNMENT_SCALE } from './useDigitalPropAlignment';

const style = {
  '--deckgo-drr-border': '1px solid #313d4f',
  '--deckgo-drr-anchor-background': '#313d4f',
  '--deckgo-drr-rotate-anchor-action-border': '1px solid #313d4f',
  '--deckgo-drr-rotate-anchor-presentation-border-right': '1px solid #313d4f',
};

export default function DrrElement({ width, height, x, y, rotate, children, onDrrDidChange }) {
  const elementRef = useRef();

  useEffect(() => {
    const ref = elementRef.current;
    if (!ref) return;
    ref.addEventListener('drrDidChange', onDrrDidChange, true);

    return () => ref.removeEventListener('drrDidChange', onDrrDidChange, true);
  }, [onDrrDidChange]);

  return (
    <deckgo-drr
      drag="all"
      unit="px"
      ref={elementRef}
      style={{
        ...style,
        '--width': `${width}px`,
        '--height': `${height}px`,
        '--top': `${y * ALIGNMENT_SCALE}px`,
        '--left': `${x * ALIGNMENT_SCALE}px`,
        '--rotate': `${rotate || 0}deg`,
      }}
    >
      {children}
    </deckgo-drr>
  );
}
```

</details>

### Environment

- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by peterpeterparker** [comment]
Thank you for the issue @mariasiuvlad

Is your project open source? Can I check it out to give a try?

As you can see in the component's [code](https://github.com/deckgo/deckdeckgo/blob/17a1961c2bd6b02ca43182b27648cdb6a811c640/webcomponents/drag-resize-rotate/src/components/deckdeckgo-drr.tsx#L137), the listeners are attached to the `document` therefore not sure why they would not be called.

Except maybe if on your button the events `propagation` is explicitly stopped?

This would maybe have for effect to not clean / release  its state?

Not sure, I would need to debug therefore would need a sample repo to reproduce the error.

**Comment by mariasiuvlad** [comment]
Hi @peterpeterparker,

Unfortunately the project is not open source.

While setting up a demo repo I did some more debugging and found the issue was being caused by something unrelated to the Drag, Resize, Rotate web component. I managed to fix the issue since then. I think this can be closed.

Thank you for your support :)

**Comment by peterpeterparker** [comment]
@ mariasiuvlad glad to hear you found a solution 👍

I close the issue but, for sure, ping me anytime if it would happens again. Have fun!
