### ISSUE TITLE
Export the Presentation as PDF via Stencil SSG

### ISSUE THREAD

**Issue by bjesuiter** [deckgo/deckdeckgo#1058]
### Affected part of DeckDeckGo

- [x] Studio (online editor)
- [ ] Remote control
- [ ] Poll
- [ ] Site
- [ ] Documentation
- [ ] Demo
- [x] Starter kit (maybe)
- [ ] Web Components
- [ ] Templates

### Feature Description

Since Stencil supports Static Site Generation now, 
this would be the perfect opportunity (i think) to implement PDF exports for the Presentation.  

Idea: 
Render the Presentation as Static Site with stencil & Print/Save it as PDF with Puppeteer. 

### Use Case

- Presentation Backups 

=> Backing Up Presentations as App-Sourcecode may be fine for Developers,  but even for a Developer like me it's easier to Backup Presentations as PDF on the file system. 

PDF is way easier to handle on normal file systems than these App Packages & I like to have all my Presentations in my Cloud Storage for further reference.

**Comment by peterpeterparker** [comment]
Thank you for the  issue @bjesuiter

Agree with you but, currently, this is something we scheduled to be included in our offering for enterprise / business.

That being said, nothing is written in stone and, it might change in the future.
