### ISSUE TITLE
add prettier to starter kit

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#1087]
### Affected part of DeckDeckGo

- [X] Starter kit

### Feature Description

I ran a [poll](https://twitter.com/daviddalbusco/status/1361722925259358210) on Twitter and 93% of voters are for Prettier as default formatter for the [starter kit](https://github.com/deckgo/starter-kit).

Therefore we should process, voters  have spoken.

**Comment by thomasledoux1** [comment]
Hey @peterpeterparker,
Which prettier config would you want to use for the starter kit?
The same as the one being used in the main repo? https://github.com/deckgo/deckdeckgo/blob/main/cli/.prettierrc

**Comment by peterpeterparker** [comment]
I would say yes @thomasledoux1 or maybe with the extra css part from this [one](https://github.com/deckgo/figma-deckdeckgo-plugin/blob/main/.prettierrc)

but I am open to suggestion of improvements, if you've got idea, totally open

**Comment by thomasledoux1** [comment]
Sure, we can add the CSS part from the Figma plugin.
I personally start from the prettier config from Kent C Dodds, because I really trust that he uses the best tools and rules in general :).
https://github.com/kentcdodds/kcd-scripts/blob/main/src/config/prettierrc.js

**Comment by peterpeterparker** [comment]
Works for me too, maybe can we use 140 as length instead of 80?

For the rest why not, we would just have to test it by formatting the `index.html` of the starter, which is the important part, works fine. Just to be sure that nothing conflicts but I guess it should be fine.

**Comment by peterpeterparker** [comment]
Solved with PR https://github.com/deckgo/starter-kit/pull/62
