### ISSUE TITLE
studio: add telegram to web-social-share options

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#1090]
### Affected part of DeckDeckGo

- [X] Studio (online editor)

### Feature Description

Add "telegram" to the list of web-social-share options.

### Code

The web component is  implemented in [app-share-deck](https://github.com/deckgo/deckdeckgo/blob/master/studio/src/app/components/core/app-share-deck/app-share-deck.tsx).

For documentation see [README](https://github.com/peterpeterparker/web-social-share).

The following [SVG](https://github.com/peterpeterparker/discoverweekly.dev/blob/e0ff79067f88edbbd9d9441b14d08eabf3b9bfc0/src/components/share/ShareDesktop.js#L76) can be use as icon.

**Comment by mtwn105** [comment]
Hi @peterpeterparker  

I would like to work on this one

**Comment by peterpeterparker** [comment]
Awesome @mtwn105 👍 
Go for it, thx

**Comment by mtwn105** [comment]
Hi @peterpeterparker 

Opened PR #1092

**Comment by peterpeterparker** [comment]
Awesome! Thx 😃
