### ISSUE TITLE
Notes encoding text incorrectly

### ISSUE THREAD

**Issue by clicketyclackety** [deckgo/deckdeckgo#1105]
### Affected part of DeckDeckGo

- [x] Studio (online editor)
- [ ] Remote control
- [ ] Poll
- [ ] Site
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Web Components
- [ ] Templates

### Reproduction

Steps to reproduce:

1. Create notes with special characters in
2. Save notes
3. View notes (see the strange encoding)

### Expected Behavior 
I expected the notes to not html~ise characters
e.g. - I'm pretty sure I heard \<insert random name> ask...

### Actual Behavior 
Notes seem to encode the saved text as if html (is this ASCII?) as opposed to just normal (UTF-8?)
e.g. - I'm pretty sure I heard &amp;lt;insert random name&amp;gt; ask...

### Environment 

- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows10

**Comment by peterpeterparker** [comment]
Thx for the issue! Can you provide a concrete sentence which leads to the unexpected result @clicketyclackety ?

**Comment by clicketyclackety** [comment]
> Thx for the issue! Can you provide a concrete sentence which leads to the unexpected result @clicketyclackety ?

The e.g in expected vs actual behaviour was meant to be this 😊

**Comment by peterpeterparker** [comment]
Sorry my bad. All good, will try. These are probably expected because either because of Markdown or the communication with the remote. Will see if we can do something...

**Comment by peterpeterparker** [comment]
@clicketyclackety had more time and energy than expected so I was able to fix that one too today 😉

thanks for all the useful feedback!

**Comment by clicketyclackety** [comment]
Quality! Thanks @peterpeterparker, I tested notes and they're working as expected :100:!

**Comment by peterpeterparker** [comment]
Cool! Thanks for the test
