### ISSUE TITLE
Inline-editor component not working in chrome when contenteditable is inside a shadow dom

### ISSUE THREAD

**Issue by lorefnon** [deckgo/deckdeckgo#1142]
### Affected part of DeckDeckGo

- [X] Web Components

Affected web-component: inline-editor

### Reproduction

Steps to reproduce:

1. Create a contenteditable inside a shadow-dom
2. Select text inside contenteditable
3. Click on any action in the editor toolbar

### Expected Behavior

The action should update the html content inside contenteditable 

### Actual Behavior

It works as expected in firefox but not in chrome.

- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS BigSur

### Sandbox containing reproducer: 

https://codesandbox.io/s/boring-jennings-hm2nf

---

It appears the problem is that document.getSelection() API returns the selection inside shadow-dom for firefox and in case of chrome, we get a fake selection where focusNode, range.startContainer, range.endContainer etc. are all body

![image](https://user-images.githubusercontent.com/1449492/117263664-1feb0c00-ae70-11eb-85ea-3aca2dc8276c.png)

**Comment by lorefnon** [comment]
One possible solution is to detect availability of [ShadowRoot.getSelection](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) method, and if supported we can find the nearest parent shadow root and call getSelection on it.

**Comment by peterpeterparker** [comment]
hi, thanks for the issue.

sounds like a good idea to use shadowroot.getSelection 👍. It might need  more changes though as the DOM is custom manipulated (I don't use document.execCommand).

Would you like to give a try to solve the issue?

**Comment by lorefnon** [comment]
Sure @peterpeterparker Thanks for your reply. 

I currently don't have much familiarity with the code but I'll see if I can explore and come up with a working PR over next 4-5 days. 

I really love the UX of the component.

**Comment by peterpeterparker** [comment]
Awesome! Ping me if you have any questions or observations.

Source are there -> https://github.com/deckgo/deckdeckgo/tree/main/webcomponents/inline-editor

**Comment by lorefnon** [comment]
> It might need more changes though as the DOM is custom manipulated (I don't use document.execCommand).

Ok, that actually creates a bigger issue for me because undo/redo does not work out of the box for styling changes (I just assumed that they would). So I'll need to check into managing undo stack at application level :\

**Comment by peterpeterparker** [comment]
Yes that's a drawback. I don't know what's the timeframe of the `execCommand` deprecation and when Input Level 2 will be introduced, so it's kind  of  a  safe bet with custom code.

https://stackoverflow.com/questions/60581285/execcommand-is-now-obsolete-whats-the-alternative

**Comment by peterpeterparker** [comment]
Being said, maybe we can reintroduce `execCommand` and keep current implementation as backup plan. Open to discussion.

**Comment by lorefnon** [comment]
So one simple & minimal solution for the original problem is that we make the displayTools an exposed method which consumers can call passing in a Selection which they have obtained from their own shadow root.

**Comment by peterpeterparker** [comment]
Sounds good to me. I'm afk, I'll review the PR later today or tomorrow.

**Comment by lorefnon** [comment]
Sure. Thanks @peterpeterparker .

**Comment by peterpeterparker** [comment]
Thanks a lot for the PR @lorefnon !

It has been merged and published to npm in version `v3.4.0`

**Comment by lorefnon** [comment]
Awesome thank you 🙂

**Comment by peterpeterparker** [comment]
@lorefnon FYI I just released v4.0.0 which re-introduces `execCommand` (default).

Optionally, through a property `command` the custom manipulation can be activated.

**Comment by lorefnon** [comment]
Nice :) Thank you. I know that execCommand is deprecated but given the platform's past track record it is very likely that it will outlive my hobby project.

**Comment by peterpeterparker** [comment]
Haha yes and in worst case, the custom implementation is still here ;)
