### ISSUE TITLE
Highlight Code: Option for horizontal scrolling

### ISSUE THREAD

**Issue by skuntze** [deckgo/deckdeckgo#1178]
### Affected part of DeckDeckGo

- [x] Web Components

Highlight Code

### Feature Description

Option for controlling the horizontal scroll behaviour/line breaks of the code.

### Use Case

In some situations, source code is easier to read if the lines are not broken. So it is better to accept the otherwise undesirable option of having a horizontal scrollbar.

![image](https://user-images.githubusercontent.com/3451457/119689569-408ffb80-be49-11eb-98c3-77e5275ee9c2.png)

**Comment by peterpeterparker** [comment]
Thanks for the issue @skuntze !

Do you mean an option in the component itself or, in our online editor?

### Component

If component itself, there are already some `overflow` CSS variables available. Maybe it can already be achieved by modifying these property from `auto` to `overflow`  ?

For example:

--deckgo-highlight-code-scroll
--deckgo-highlight-code-carbon-overflow

https://docs.deckdeckgo.com/?path=/docs/components-highlight-code--highlight-code

Can you check if it works out? 

If not, sure let's see what we should add for option for such purpose.

### Editor

If you meant in the online editor, then not sure. The goal being to display a slide to the audience so maybe its better to modify the font size to always make everything appear in block?

**Comment by skuntze** [comment]
@peterpeterparker Thanks for the reply!

I mean the option in the component, not the online editor.

Could you share an example of how to use these CSS variables?

**Comment by peterpeterparker** [comment]
For example, you can you either use the CSS variables inlined

```
<deckgo-highlight-code style="--deckgo-highlight-code-scroll: scroll;">
</deckgo-highlight-code>
```

Or in CSS class

```
deckgo-highlight-code {
    --deckgo-highlight-code-scroll: scroll;
}
```

Let me know if it works out

**Comment by skuntze** [comment]
Thanks for your support, @peterpeterparker.

This CSS variable is indeed adding scrollbars to the component but the code lines seem to be broken before (the line numbers also change).

![highlight-code-scroll](https://user-images.githubusercontent.com/3451457/119838309-9923cf00-bf03-11eb-9ef0-8088213b7026.gif)

Hopefully uploading a GIF works fine...

**Comment by peterpeterparker** [comment]
You may have to tweak some other CSS variables, assuming these are available but, not totally sure.

Is your project open source? If not, can you provide a sample repo?

**Comment by skuntze** [comment]
@peterpeterparker Unfortunately, the project is not open source. I will try my best to provide a sample repo to you soon.

**Comment by peterpeterparker** [comment]
Thx for the sample repo @skuntze 

I have added a new CSS variable for your use case and released in version `v3.2.0` of the component.

```
deckgo-highlight-code {
        --deckgo-highlight-code-width: max-content;
}
```

Should solve your use case. Let me know if it works out.

<img width="1513" alt="Capture d’écran 2021-05-29 à 09 40 28" src="https://user-images.githubusercontent.com/16886711/120062341-00f02c00-c062-11eb-893a-c94c840be9d6.png">

**Comment by skuntze** [comment]
@peterpeterparker Thank you so much for your quick support. That's exactly what we were looking for! 🙂

**Comment by peterpeterparker** [comment]
Awesome, happy to hear that, thank you for your help!
