### ISSUE TITLE
--deckgo-inline-editor-button-zindex

### ISSUE THREAD

**Issue by phpmydev** [deckgo/deckdeckgo#1213]
How do I implement this? thanks!  the toolbar is showing behind the last comment in my app
also where do I change command to custom? I do not wish to have the undo/redo functions provided by the deprecated execCommand - I am using the unpkg cdn

**Comment by phpmydev** [comment]
![image](https://user-images.githubusercontent.com/746353/123163620-c5f5d400-d426-11eb-9eea-0d2ddcce3188.png)

**Comment by phpmydev** [comment]
when I try to position deckgo element it does not display at all, and I cannot give a z-index to a non-positioned element.
Can @peterpeterparker explain?  What am I doing wrong?

**Comment by phpmydev** [comment]
tried adding  [1, 'deckgo-ie-zindex', {
            zIndex: [100000]
        }], and variations to the array in the js file - no luck :(

**Comment by phpmydev** [comment]
I figured it out, it's in the entry.js file imported from the one from the cdn.  Look for zindex throughout and change the values to 100000

**Comment by peterpeterparker** [comment]
`--deckgo-inline-editor-button-zindex` is a CSS variable, you can use it by applying through the `style` or in a `class` of the component or one of its parent.

but if you generally as an issue with `z-index` I would use the `--deckgo-inline-editor-zindex` which is the value  of the all toolbar.

```
<deckgo-inline-editor style="--deckgo-inline-editor-zindex:  1000">
</deckgo-inline-editor>
```
