### ISSUE TITLE
User accounts: add update username and delete user

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#125]

**Comment by peterpeterparker** [comment]
@nmattia I tried the endpoint API to update a user's username and I received a 405

I guess it is just not yet implemented on the API side right?

**Comment by peterpeterparker** [comment]
@nmattia deployed on staging

update username: implemented but as described above, there is a bug somewhere
delete: implemented and all good

**Comment by peterpeterparker** [comment]
update username: it seems that updating username actually set username to null and anonymous to true...something weird somewhere

**Comment by nmattia** [comment]
@peterpeterparker this is actually done, right? There was an issue when calling the API?

**Comment by peterpeterparker** [comment]
We still have to double check "update username", last time I tried it was weird somewhere
