### ISSUE TITLE
Why not one

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo#126]
FYI

Re this commit: https://github.com/deckgo/deckdeckgo/commit/2e08b03be0f64322295ef9e5a0761e0e102bb0fa

Update problem to 18.1 here: https://github.com/edgarordonez/d3-stencil/pull/31
at this point: https://github.com/edgarordonez/d3-stencil/pull/31#issuecomment-493259092

Possible cause here: https://github.com/rollup/rollup/issues/2865

If you run into the same problem then please flag it upstream.

**Comment by peterpeterparker** [comment]
cool @peterennis thx for pointing this out 👍 

I developed the component lazy-img with Stencil One, it worked fine but when I tried to use it in one or our PWA build with Stencil v0.18.0 I wasn't able to import/use it, that's why I rollbacked

Will keep an eye on that

**Comment by peterpeterparker** [comment]
@peterennis done ;)

all components and PWAs from our projects have been upgraded to Stencil One! ping me if you notice anything and thx for the issue
