### ISSUE TITLE
lazy img loads everything?

### ISSUE THREAD

**Issue by joekingTheThird3** [deckgo/deckdeckgo#128]
I think maybe I don't understand the component  or the thing seems to load all the pictures.
I expected to have the first picture loaded with the following pictures which were off screen not loaded. But judging by the scroll bar and in the developers tools then all the pictures are loaded even if they are off screen. I am using firefox 66.0.5 64bit.  An observation: if I refresh the page then I quickly see the alt text then all the images replacing the alt text.

**Comment by peterpeterparker** [comment]
@joekingTheThird3 thx for the feedback

> I expected to have the first picture loaded with the following pictures which were off screen not loaded. 

correct expectation

> But judging by the scroll bar and in the developers tools then all the pictures are loaded even if they are off screen.

you can't I think rely on the scroll bar to check if the images are loaded or not. to double check if the images are loaded or not you could either observe the "network" of your debugger to see when images are loaded or not or have a look to the DOM. If everything work as expected, images `src` attributes should only be provided the images enter the viewport ("no more offscreen")

When not loaded:

```
<deckgo-lazy-img>
   #shadowroot
        <img data-src="">
```

and when loaded (img attribute should change):

```
<deckgo-lazy-img>
   #shadowroot
        <img src="">
```

could you double check? if still not good, could you provide me some more details, would be of course happy to have a deeper look

Thx in advance

**Comment by joekingTheThird3** [comment]
I have a codepen test which has most of my original code and pics. Still, this seems to load all the pics even the offscreen pics.   
https://codepen.io/joeKingtheThird/pen/qGPEaV

I have some grabs of the inspector - this seems to show the src attribute on the image tag on all 4 of the web components - grab from my local file html
![snap0897](https://user-images.githubusercontent.com/47086018/58021399-b185d580-7b02-11e9-841e-eaff4024ba15.png)

**Comment by peterpeterparker** [comment]
cool @joekingTheThird3, thx for the codepen and details, I observe in codepen the same behavior

I'm not sure but I would say that the problem might be linked to the fact that the content is rendered and displayed by codepen in a frame. Without frame, same content, all images are lazy loaded

<img width="1192" alt="Capture d’écran 2019-05-20 à 14 43 08" src="https://user-images.githubusercontent.com/16886711/58022774-79848f80-7b0e-11e9-8c2b-6b92e15cada3.png">

<img width="1192" alt="Capture d’écran 2019-05-20 à 14 43 13" src="https://user-images.githubusercontent.com/16886711/58022784-81dcca80-7b0e-11e9-94fe-fbd7fb97cb0e.png">

**Comment by joekingTheThird3** [comment]
This is the markup I have for a local file. Imgs are on imgur.com - all images loaded even offscreen (the ones at the bottom)
<!DOCTYPE html>
<html lang="en">
<head>
<script src="https://unpkg.com/deckdeckgo-lazy-img@latest/dist/deckdeckgo-lazy-img.js"></script>
</head>
<body>
<style>
div{
background:#f00;
//height:200px;
overflow:scroll;

}
:root{
--deckgo-lazy-img-padding:20px;
}
</style>



<div>
  <deckgo-lazy-img
    img-src="https://i.imgur.com/2pfzSzA.jpg"
    img-alt="My lazy loaded image">
  </deckgo-lazy-img>


<deckgo-lazy-img
    img-src="https://i.imgur.com/YqsFork.jpg"
    img-alt="My lazy loaded image">
</deckgo-lazy-img>



  <deckgo-lazy-img
    img-src="https://i.imgur.com/bRqhrC5.jpg"
    img-alt="My lazy loaded image">
  </deckgo-lazy-img>
  
  
    <deckgo-lazy-img
      img-src="https://i.imgur.com/xdzMKJB.jpg"
      img-alt="My lazy loaded image">
  </deckgo-lazy-img>





</div>




  


</body>
</html>

**Comment by peterpeterparker** [comment]
@joekingTheThird3 gotcha thx!

as the content contains only images, when nothing is loaded, all images are in the viewport, therefore the intersection is triggered

content:

x
x
x
x
---end of viewport

if you add a style like:

```
deckgo-lazy-img {
    display: block;
    min-height: 400px;
  }
```

it fix the issue as the images are spaced

x
--- end of viewport
x
x
x

I should think about if it need a default value in the component or an entry in the documentation. I guess in a real use case the page where the component will be use will contains content and therefore the images will be spaced and placed outside of the viewport

**Comment by joekingTheThird3** [comment]
I thought there was a prob with IntersectionObserver but in the console
"IntersectionObserver" in window
true

**Comment by peterpeterparker** [comment]
@joekingTheThird3 we commented the issue in the same time ;)

add content in the page or default height to the components and you should be fine

**Comment by joekingTheThird3** [comment]
Aha, I put your bit of styling in the file and actually I went right down the page and then refreshed the page. Aha! So, the last image shows and the previous image doesn't show until I scroll back up to bring the image into the viewport. I should have had more content to help this lazy loading?

**Comment by peterpeterparker** [comment]
Yes content or a default component height in order to put the images outside of the view port, specially if the goal is to test the component

But like I said, will think about it. Either I set a default height or I add a note in the documentation about it

**Comment by peterpeterparker** [comment]
Thx 👍

**Comment by peterpeterparker** [comment]
I have added a note in the documentation (https://docs.deckdeckgo.com/components/lazy-img) about it. Thx for your feedback 👍

**Comment by joekingTheThird3** [comment]
Ok, I see the note you have made in your documentation.

 

Maybe this a feature request, could you have a placeholder src for the component. Usually with the lazy load procedure the src holds a lowres pic or loading spinner with the actual image in  a data-src which is swapped to the src when it gets in view. You have the img-src for the src.

 

Sent: Tuesday, May 21, 2019 at 6:22 AM

**Comment by peterpeterparker** [comment]
@joekingTheThird3 we might need that someday too, not yet yet but someday. spontaneously I would think about adding a `<slot/>` to the component for that purpose. thx for the hint 👍 

I've open a feature request about it: https://github.com/deckgo/deckdeckgo/issues/129
