### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by rajeevb2** [deckgo/deckdeckgo#1444]
Was playing with Deckdeckgo. A couple questions
1. The website seems to have interactive slide editing but the npm start run option seems to say you have to edit HTML. Do you support interactive slide editing with the local install
2. Do you support comments on the slides

**Comment by peterpeterparker** [comment]
Hi,

1. `npm init deckdeckgo` create a presentation that can be developed with HTML ([docs](https://docs.deckdeckgo.com/?path=/story/introduction-getting-started--page)). "studio" is our [online](https://app.deckdeckgo.com) WYSIWYG editor.

2. Both with the developer kit ([docs](https://docs.deckdeckgo.com/?path=/story/edit-notes--page)) and the online editor support "notes"

For any questions, feel free to reach out per mail or on slack ([contact](https://deckdeckgo.com/en/contact)).
