### ISSUE TITLE
Long Lines in Code Highlighter Wrap to the Next Line.

### ISSUE THREAD

**Issue by Bradleykingz** [deckgo/deckdeckgo#1466]
### Affected part of DeckDeckGo

- [ ] Studio (online editor)
- [ ] Remote control
- [ ] Poll
- [ ] Site
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [X] Web Components
- [ ] Templates

### Reproduction

Steps to reproduce:

1. Add code to code highlighter
2. Long text wraps to the next line

### Expected Behavior
Long lines of text should not wrap. They should be scrollable horizontally.

### Actual Behavior

![image](https://user-images.githubusercontent.com/19578478/152632995-e33e4cc8-6104-462b-946a-636ddc597aad.png)

Long lines in a small container wrap to the next line, making it difficult to read the code. Could it be possible to make them scrollable horizontally instead?

### Environment

Web

**Comment by peterpeterparker** [comment]
Hi, it is actually already supported. If you wish to not wrap the lines, you can apply following style:

```
--deckgo-highlight-code-white-space: pre;
```

If it would not work, let me know.

**Comment by Bradleykingz** [comment]
Perfect. Thanks.
