### ISSUE TITLE
Studio starter

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#148]
- Branch or repo or mono-repo with all three (html, markdown and studio) starters: I would say mono repo if clone possible

TODO:

- add replace keys to replace content with presentation
- remove demo content in index.html
- remove unused libs: No (for simplicity/merge reason)
- update ROOM name for remote control (like website with a random number): Done
- remove unused ionicons: Done
- option to not display control and pager in fullscreen: Done (http://localhost:3000/?screenshot)

All starters:

- web platform share and fallback on web-social-share: Done
- hide fab actions on inactivity fullscreen: Done
- update popover/menu "actions" slots with DeckDeckGo:  Done

**Comment by peterpeterparker** [comment]
For the icons, it will need an improvement in Ionic if we stick to Fab button: https://github.com/ionic-team/ionic/issues/18442

**Comment by nmattia** [comment]
@peterpeterparker this is done, right?

**Comment by peterpeterparker** [comment]
Well no, again, sorry

**Comment by peterpeterparker** [comment]
@nmattia yes it is

just one more key need to be actualized but that's in https://github.com/deckgo/deckdeckgo/issues/149
