### ISSUE TITLE
Return publication URL on “publish”

### ISSUE THREAD

**Issue by nmattia** [deckgo/deckdeckgo#175]
When performing a `POST /decks/<deck id>/publish`, the backend should return the publication URL:
```
{ “publish_url” : “https://.../foo/my-pres/“ }
```

**Comment by peterpeterparker** [comment]
Would probably be more handy to just gives back the "contextId" /my-pres/ if possible?

When I do a decks.GET, I'll get the "contextId" back too right?

If so I could handle the URL always in the same way aka "https://..." with a constant, "/foo" = username and "/my-pres" with deck.contextId (or whatever the name of the variable)

**Comment by peterpeterparker** [comment]
Has been implemented
