### ISSUE TITLE
publish: div slot="background"

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#177]
The background for the all deck doesn't seems to be correctly parsed during publishing:

1. div slot="background" is missing
2. seems to be parsed as Text

Is (see screenshot)

Should

```
     <deckgo-deck>
          <!-- all slides -->
         
          <div slot="background>
               <!-- parse the content here -->
          </div>
      </deckgo-deck>
```

<img width="1173" alt="Capture d’écran 2019-06-13 à 07 12 48" src="https://user-images.githubusercontent.com/16886711/59405404-b577e100-8daa-11e9-84a7-d14fea2aada7.png">

**Comment by nmattia** [comment]
yep, had a brainfart last night. Pushing a fix.

**Comment by peterpeterparker** [comment]
Tested 27th August 2019, all good
