### ISSUE TITLE
screen formatting - Android LG K20 V

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo#188]
Here

![ddg1](https://user-images.githubusercontent.com/140737/59457246-e8cb6780-8dcc-11e9-91a8-17d1e0782d55.jpg)

**Comment by peterpeterparker** [comment]
@peterennis thx 👍  should be good now, if not ping me (https://github.com/deckgo/deckdeckgo-website/commit/555ddcf2656223553480b06173a1fe970ffafd75)
