### ISSUE TITLE
[docs] Improve demo slides in the documentation

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#199]
## Description

Slides (= demo slides) are presented in the documentation. These are also presented with dummy content provided as slots, for example content like (as text) "slot=title". 

I received the feedback that it isn't very clear, specially their spacing (how big are slots? which spaces are they using? which alignment? etc.)

Example: https://docs.deckdeckgo.com/slides/concept

## Solution

The idea is to highlight the slot a bit more by adding a `border` to these.

## Tech solution

This could probably been solved by applying global Css style on the documentation.

For example something like:

```
deckgo-deck {
   h1, h2, h3, section, deckgo-highlight-code {
    border-radius: 2px;
    border: 1px solid var(--ion-color-primary);
  }
```

The documentation style finds place in [docs/src/global/theme](https://github.com/deckgo/deckdeckgo/tree/master/docs/src/global/theme)

## Get started

Interested to get involved and to try to implement this enhancement? Ping me if you have any questions or need help to get started, David (@peterpeterparker or [twitter.com/daviddalbusco](https://twitter.com/daviddalbusco)) 😃

## Notabene

The [docs](https://github.com/deckgo/deckdeckgo/tree/master/docs) PWA of DeckDeckGo is written in Markdown. The source of the documentation finds place in [docs/docs](https://github.com/deckgo/deckdeckgo/tree/master/docs/).

When `npm run start` or `npm run build` are run, the Markdown will be transformed into HTML which gonna be automatically added into the TSX files. Both should be added to Git.

If the documentation Markdown files is modified, currently, there isn't any live reload (unfortunately). Therefor, the cmd should be started again, sorry for the inconvenience.

**Comment by peterpeterparker** [comment]
We should probably display something like the following mockup:

<img width="1221" alt="Capture d’écran 2019-07-25 à 15 41 07" src="https://user-images.githubusercontent.com/16886711/61879128-c01dae00-aef2-11e9-96f7-c53a3d4dcd5b.png">

**Comment by StefanNieuwenhuis** [comment]
I'm on it!
