### ISSUE TITLE
Slides are not centered on chrome on iPadOS

### ISSUE THREAD

**Issue by nmattia** [deckgo/deckdeckgo#212]
<img width="1366" alt="Screenshot 2019-07-28 at 21 43 06" src="https://user-images.githubusercontent.com/6930756/62012014-ef494f00-b180-11e9-9c97-2d1abf608fb2.png">

**Comment by peterpeterparker** [comment]
Yep same. I guess, `window.width` and `screen.width` doesn't work on iPad

<img width="959" alt="Capture d’écran 2019-07-28 à 21 48 31" src="https://user-images.githubusercontent.com/16886711/62012059-86aea200-b181-11e9-8f85-3bc6498b1f2a.png">

**Comment by peterpeterparker** [comment]
On iOS it seems than sometimes `screen.width` is the property to use to determine the screen size, sometime it's `window.innerWidth`, because why not probably

Solved in next core release and will need an update of all starter branch and website
