### ISSUE TITLE
overflow scroll ?

### ISSUE THREAD

**Issue by noelmace** [deckgo/deckdeckgo#237]
On the demo, or when starting a new project using deckdeckgo-starter, the first slide looks like this
 
![image](https://user-images.githubusercontent.com/7578400/63757454-5bbb8900-c8ba-11e9-85f6-1af0d636a861.png)

This is due to an overflow: scroll introduced by https://github.com/deckgo/deckdeckgo/commit/12a843dc462fccb1e15426243ca5dccc55481c3a

https://github.com/deckgo/deckdeckgo/blob/e27acdf3b65a2e59edb5760d1879139117f9d9e2/studio/src/global/theme/editor/editor-deck-deck.scss#L15-L19

browser: Chrome 78.0.3876.0 & Firefox 69.0b15
version: starter 1.0.0-beta.22

**Comment by peterpeterparker** [comment]
Raaah ptain :(

Windows or Linux?

On my Mac, Chrome or Firefox, starter-kit and website are both ok.

P.S.: Thx for opening an issue about it 👍 

<img width="1440" alt="Capture d’écran 2019-08-27 à 11 39 44" src="https://user-images.githubusercontent.com/16886711/63760444-9d9afe00-c8bf-11e9-88dc-778bfc598321.png">
<img width="1438" alt="Capture d’écran 2019-08-27 à 11 40 20" src="https://user-images.githubusercontent.com/16886711/63760445-9d9afe00-c8bf-11e9-8456-371d85dac1f1.png">

**Comment by noelmace** [comment]
Linux

**Comment by peterpeterparker** [comment]
Thx for the feedback 👍 

I guess I just have to change the `scroll` to `auto` and it should be solved and still compatible with our upcoming editor. I'll meet @nmattia later today, I will test it first on his linux laptop

**Comment by noelmace** [comment]
I'm confused ... how is it related to the OS?

**Comment by peterpeterparker** [comment]
Me too not sure why but I think I already faced that kind of same weird behavior with another element a couple of weeks/months ago. No scrollbars were displayed on my Mac but some were displayed on Nicolas' linux machine.

I'm just guessing that it might be the case again.

Anyway I guess `auto` is the solution, just wand to be sure I'll fix it once for all ;)

**Comment by noelmace** [comment]
That's really weird indeed :smile: I'd be very interessed to know the root cause if you find it!

**Comment by peterpeterparker** [comment]
Might actually be an "OSX issue" or the fact that on OSX scrollbars are (per default) most of the time hidden by the system, that's why I thought it was all good probably 😒

See screenshots when I "force" OSX to display the scrolls

<img width="1440" alt="Capture d’écran 2019-08-27 à 12 39 54" src="https://user-images.githubusercontent.com/16886711/63764905-29b12380-c8c8-11e9-8993-3e62cfb57d00.png">
<img width="1440" alt="Capture d’écran 2019-08-27 à 12 40 04" src="https://user-images.githubusercontent.com/16886711/63764906-2a49ba00-c8c8-11e9-8e50-2768d51fc09b.png">

**Comment by noelmace** [comment]
This is good to know thx!

**Comment by peterpeterparker** [comment]
`auto` updated in website, starter and studio. still need to double check but should be good

**Comment by peterpeterparker** [comment]
Tested on Linux, looks good now

But I would be happy if you could double check @noelmace 

Thx for reporting the issue

**Comment by noelmace** [comment]
LGTM :ok_hand: Thx

**Comment by peterpeterparker** [comment]
Awesome, thx for the feedback!
