### ISSUE TITLE
Tagging completes on pause, not on enter

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo#256]
The autocomplete for tagging is aggressive. Value is entered at some pause.
Fixing means I have to delete entries and type fast again with no pause.

![ddg-auto-tag](https://user-images.githubusercontent.com/140737/63960911-6bff6f80-ca44-11e9-9e84-c1c55f640f19.gif)

**Comment by peterpeterparker** [comment]
Thx for the feedback 👍 

Of course I'm not against increasing the delay.

Could you send me a PR?

Spontaneously I would say that the following is the "debounce" time to increase: https://github.com/deckgo/deckdeckgo/blob/965f74e3f393e270243cc4040bbbb17c57f9260b/studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.tsx#L338

**Comment by peterennis** [comment]
@peterpeterparker 
I noticed that debounceTime is imported and used once, while debounce={500}
is used 3 times in that code.
Not sure what value to change.
A defined const may be better.

**Comment by peterpeterparker** [comment]
@peterennis the one I linked above. But no worries, I could do it then ;)

what would you suggest, 1sec or more? 
or just no debounce and when "space" or "," are used, then the tag is added?

**Comment by peterennis** [comment]
@peterpeterparker 
1. I am not sure what debounce is really doing so cannot answer the time.
2. Typical form entry uses "Enter" for completion.
3. If you define a tag as a single word item with no space then "Space" is a good choice.
4. On screen help? e.g. "Press space to complete tag entry"
5, I do not think comma is a good choice.

**Comment by peterpeterparker** [comment]
@peterennis thx for the inputs 👍 

I'm not a fan of the comma neither but I think it's how youtube and medium works actually, but maybe they offer more option. I'll look how they behave

**Comment by peterpeterparker** [comment]
I have removed the debounce. Tags are only going to be added once user will hit `space`, `,` or `enter`.

I checked how other platforms handle tags.

Note regarding `space`: I think we are going to handle more easily tags without spaces, that's why I sticked to that solution

Thx for your inputs 👍
