### ISSUE TITLE
republish does not show changes - caching?

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo#266]
Update page and republish

![Capture678](https://user-images.githubusercontent.com/140737/64058269-72cdd580-cb5d-11e9-9744-15c858cae8bf.png)

Old version displayed

![Capture679](https://user-images.githubusercontent.com/140737/64058274-78c3b680-cb5d-11e9-9e22-2af2141758f5.png)

Reopen in Chrome private browsing

![Capture680](https://user-images.githubusercontent.com/140737/64058277-7eb99780-cb5d-11e9-8b0e-9e637a517455.png)

Looks like the local cache is not refreshed

**Comment by peterpeterparker** [comment]
Thx!

There is an open task regarding caching. (https://github.com/deckgo/deckdeckgo/issues/167), therefore I close this one.

But generally speaking the presentations are Progressive Web Apps, that's why there caching is pretty solid ;)
