### ISSUE TITLE
bold option missing on title header

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo#267]
![Capture681](https://user-images.githubusercontent.com/140737/64058842-263ac800-cb66-11e9-8905-111679a600fe.png)

**Comment by peterpeterparker** [comment]
Thx for the issue and test! Yep this is per design.

"bold" doesn't work well with content editable, depending of the font and font-weight then the bold might not be bold but triggers a font normal, kind of weird effect.

Other WYSIWYG editors like for example Medium have no bold option on title too.

**Comment by peterpeterparker** [comment]
P.S.: Not that you have to believe me, but I already spent a couple of hours experimenting with this 🤣
