### ISSUE TITLE
Webpack plugin markdown: npm run start 

### ISSUE THREAD

**Issue by loquace** [deckgo/deckdeckgo#283]
Hi,
I have an issue running a deck for the first time.
I just followed the steps to locally a deckdeckgo presentation.
npm init deckdeckgo
--- answered the questions, **choosing markdown at the end**
--- ran npm run start
And get the following issue =>
 Child HtmlWebpackCompiler:
[0]      1 asset
[0]     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
[0]     [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 5.48 KiB {HtmlWebpackPlugin_0} [built]
[0] /home/seb/Projets/super-prez/node_modules/deckdeckgo-webpack-plugins/lib/markdown/deckdeckgo-markdown-plugin.js:42
[0]             this.md = new Remarkable({
[0]                       ^
[0] 
[0] TypeError: Remarkable is not a constructor
[0]     at DeckDeckGoMarkdownPlugin.renderMarkdown (/home/seb/Projets/super-prez/node_modules/deckdeckgo-webpack-plugins/lib/markdown/deckdeckgo-markdown-plugin.js:42:23)
etc....

**Nodejs version** = v12.6.0

As I just get into the project I do not know if the error can occur because of me or if this is an issue. I post anyway.

Best regards

**Comment by peterpeterparker** [comment]
@loquace freak sorry, my bad, it's a bug!

I'll fix that after work later today if it's ok for you?

It's related to `remarkable`, I should update the related code in the webpack markdown plugin, there were some breaking changes in their v2 libs

**Comment by loquace** [comment]
@peterpeterparker 
Absolutely no problem for me. I just get interested into contributing because of your inspiring post on dev.to. So the first thing was to look at what it looks like :)

I have just tested a new one with html editing style : Works fine !
I continue my helicopter tour. I do not know Ionic but I am quite at ease with angular and some other technos.

**Comment by loquace** [comment]
...and do not feel sorry, your awsome !

**Comment by peterpeterparker** [comment]
@loquace haha thx for being so nice, I should have avoided this bug ;)

cool to know you are interesting to contribute, that would be super duper cool!

let me know if you have any questions or ideas

**Comment by peterpeterparker** [comment]
Fixed @loquace 

You could either begin a new deck `npm init deckdeckgo` (the fix has been deployed in our starter kit) or uninstall and install again the following lib in your markdown presentation:

```
npm rm deckdeckgo-webpack-plugins --save-dev
npm install deckdeckgo-webpack-plugins --save-dev
```

Again please excuse me for that stupid bug and thank a lot for reporting the issue, super cool 👍
