### ISSUE TITLE
pager: automatic color in case of "split" slide

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#286]
## Description

when the page is displayed on a template "split slide", then, in case no specific color are provided, it should find the automatic color to apply in the left pane of the slide aka not the overall slide background

<img width="1210" alt="Capture d’écran 2019-09-28 à 07 53 14" src="https://user-images.githubusercontent.com/16886711/65812283-442b3500-e1c5-11e9-9f54-2f6522bb7c4b.png">

**Comment by pedroapfilho** [comment]
I'll take care of this one

**Comment by peterpeterparker** [comment]
Cool @pedroapfilho 👍 

That's a bit a tricky one to test,  as you have to build your modifications in core and test it with the slide template "split"

The implementation finds place in function `initSlidePagerColor` https://github.com/deckgo/deckdeckgo/blob/96fd6bc33626e63f5d86c32f2875b186c3616697/webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx#L935

Basically, where the slide background color `--background` is tested, the test should be extended with `--slide-split-background-start` aka the either one of them should be use to set the color of pager

Same for color (not just background)

**Comment by peterpeterparker** [comment]
As of v2.2.0 we are not going to display the pager anymore, therefore, issue solved ;)
