### ISSUE TITLE
font spacing update does not stick

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo#299]
I removed spaces in the text but they show again when opening the presentation for
further development.

![Capture684](https://user-images.githubusercontent.com/140737/64215405-761cd600-ce69-11e9-9540-c0f1994a8ac4.png)

**Comment by peterpeterparker** [comment]
thx for the issue

can't reproduce it, probably linked to the fact that you faced errors (#298) and therefore it couldn't be saved
