### ISSUE TITLE
[Feature request] allow labels on x-axis when using animation with bar charts 

### ISSUE THREAD

**Issue by noelmace** [deckgo/deckdeckgo#340]
Currently, the bar-charts components allow animation for one entry (i.e. CSV line) after the other. This doesn't permit to add labels for x-axis.

## reproduce

The showcase:
https://github.com/deckgo/deckdeckgo/blob/1fa9230627b5bbfe16a46aa28148be984d6c32d7/webcomponents/charts/src/index.html#L29
show:
https://github.com/deckgo/deckdeckgo/blob/1fa9230627b5bbfe16a46aa28148be984d6c32d7/webcomponents/charts/showcase/data-bar-chart-to-compare.csv#L1
then:
https://github.com/deckgo/deckdeckgo/blob/1fa9230627b5bbfe16a46aa28148be984d6c32d7/webcomponents/charts/showcase/data-bar-chart-to-compare.csv#L2
etc...

https://github.com/deckgo/deckdeckgo/blob/1fa9230627b5bbfe16a46aa28148be984d6c32d7/webcomponents/charts/src/components/charts/deckdeckgo-bar-chart/deckdeckgo-bar-chart.tsx#L208-L210
use the 1, 2, 3 keys as x-axis labels

## solutions

1. use csv header
```csv
:date;foo;bar;baz
01.01.2018;5;0;10
01.03.2018;10;6;12
```
2. use the csv collonnes instead of rows. Using the previous csv example, this would give:
```javascript
// index === 0
{label: "01.01.2018", value: 5}
{label: "01.03.2018", value: 10}
// index === 1
{label: "01.01.2018", value: 0}
{label: "01.03.2018", value: 6}
// index === 2
{label: "01.01.2018", value: 10}
{label: "01.03.2018", value: 12}
```
IMO, solution 2 is more consistent with how this component works without animation.

**Comment by noelmace** [comment]
Also, the labels should be bigger :slightly_smiling_face:

**Comment by peterpeterparker** [comment]
Coolio 👍

I might (I'll probably) include the charts components/slides a couple weeks after the launch in our editor. Doing so, I'll have to develop some improvements in the charts slide/component (I would not be surprised if I would have to). I'll include and take care of your valuable inputs at the same time.

**Comment by peterpeterparker** [comment]
Done

```
;Salami;Pastrami;Prosciutto
01.01.2018;5;0;10
01.03.2018;10;6;12
01.06.2018;8;14;8
01.09.2018;14;8;16
01.12.2018;18;4;5
```

Thx for the idea 👍 

P.S.: Released just not rolled out in the starter kit yet
