### ISSUE TITLE
studio: background opacity and missing "white"

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#348]
Currently it's possible to apply a color on backgrounds (presentation, slides and elements) but it is not possible to set an opacity. Would probably be fancy to be able to specify such values, specially for "elements"

**Comment by bzuillsmith** [comment]
Additionally, you cannot clear a color if you accidentally assign one. I suppose this would fall under setting full opacity, though.

**Comment by peterpeterparker** [comment]
@bzuillsmith good point

yes I guess too that it would works with opacity, but maybe you have an idea for a better UX? would love to hear your idea

**Comment by peterpeterparker** [comment]
@bzuillsmith thx for the inputs. Moreover to the opacity I've add a "reset" button.

Let me know if you've got further cool ideas!

**Comment by peterpeterparker** [comment]
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/16886711/65828961-ed932900-e2a0-11e9-990a-b766cf029926.gif)
