### ISSUE TITLE
publish: cache problem might be linked to missing headers

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#355]
The current refresh problem we are facing with the published the deck, the fact that the user need to trigger an explicit refresh in order to refresh the presentation, might be linked to the fact that no headers `cache-control: no-cache` for the `service-worker.js` are defined, which I actually do in our current website (for comparison purpose).

Here's the current firebase config for the current website:

```
{
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
    "headers": [
      {
        "source": "service-worker.js",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache"
          }
        ]
      },
      {
        "source": "assets/**/*",
        "headers": [
          {
            "key": "Access-Control-Allow-Origin",
            "value": "*"
          }
        ]
      }
    ]
  }
}
```

`service-worker.js` reference `precache-manifest.hash.js` which contains for example:

```
{
    "revision": "8f047231f4689bb8b0b6e8acdf438dae",
    "url": "index.html"
  }
```

And some screenshots for comparison:

Website

<img width="1272" alt="Capture d’écran 2019-09-22 à 16 55 21" src="https://user-images.githubusercontent.com/16886711/65389800-f4c6ae00-dd59-11e9-9356-b30c3728255d.png">

Published with studio

<img width="1272" alt="Capture d’écran 2019-09-22 à 16 55 24" src="https://user-images.githubusercontent.com/16886711/65389802-f8f2cb80-dd59-11e9-9e11-3ea5c58b5950.png">

**Comment by nmattia** [comment]
But we do want to cache, right? Otherwise the user will refetch the presentation every time. I'm confused!

**Comment by peterpeterparker** [comment]
my understanding:  

if `service-worker.js` is specified without cache, yes the browser will read it again, but, it contains a list of referenced files indexed with hash values. the browser will not refresh all the files in any case but will only refresh these if they are provided with a new hash values.

hash are generated by the build aka when we publish again. so as long as there is not new publish, only the `service-worker.js` will be fetched again. if new publish, new build, new hash, then content is fetched again aka updated.

**Comment by peterpeterparker** [comment]
For next Monday @nmattia :

- Hash of filename `precache-manifest.57bed1c718fde3dfa400de7c16ee30cb.js` has to be updated => `precache-manifest.new-hash.js`

- In `service-worker.js` above filename with new hash has to be updated

```
importScripts(
  "precache-manifest.57bed1c718fde3dfa400de7c16ee30cb.js"
);
```

- Finally, I guess, in `precache-manifest.57bed1c718fde3dfa400de7c16ee30cb.js`, the `revision` of `index.html` has to be updated too (?)

```
{
    "revision": "f87d4260bcd069a80b9d9f2c1d28293a",
    "url": "index.html"
  }
```

**Comment by peterpeterparker** [comment]
and http header (maybe):

```
{
        "source": "service-worker.js",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache"
          }
        ]
      }
```

**Comment by nmattia** [comment]
Indeed, the `revision` associated with `index.html` is the md5 sum of the original index, and `foo` in `precache-manifset.<foo>.js` is the md5 sum of the precache manifest.

**Comment by peterpeterparker** [comment]
not used webpack plugins removed in the starter studio branch. reference [commit](https://github.com/deckgo/deckdeckgo-starter/commit/6a4768eba2a47b442f780863384e33303e1130ee)

**Comment by peterpeterparker** [comment]
we are going to implement a prompt to ask users to reload: #858
