### ISSUE TITLE
Spanish Translation?

### ISSUE THREAD

**Issue by mauriciolanda4** [deckgo/deckdeckgo#360]
I am willing to do english-spanish translation for this if there is a need for it.

**Comment by peterpeterparker** [comment]
@mauriciolanda4 sweat, that would be super cool!

Nicolas and I are both Swiss-french, so i18n and translations are definitely somewhere in our mind 😉

**Comment by mauriciolanda4** [comment]
Awesome, is there something prepared right now in the code so that i can start or is it for later releases?, if so i can wait :D

**Comment by peterpeterparker** [comment]
@mauriciolanda4 it would be for a later release, it is not yet ready. definitely a good idea to have opened an issue about it 👍

**Comment by mauriciolanda4** [comment]
Awesome, I will be here then and when it is time just comment on here, thanks :D

**Comment by peterpeterparker** [comment]
Before being able to translate we need to implement the i18n support. For that purpose I opened #370.

**Comment by peterpeterparker** [comment]
it is now possible to translate our editor, it took me  some times and had to  make some manual work, so really happy  about it

as I said  in other issue, if you are still in to help translate DeckDeckGo that would be over neat

**Comment by mauriciolanda4** [comment]
somehow this notification got lost on my account xd,

i would be happy to start with the spanish translation, where do i start making changes?

**Comment by peterpeterparker** [comment]
awesome @mauriciolanda4 👍

to start you can have a look at the [CONTRIBUTING](https://github.com/deckgo/deckdeckgo/blob/master/CONTRIBUTING.md#translation) guide in which I described what can be done to translate the editor and studio

Shortened, for the editor, this file [en.json](https://github.com/deckgo/deckdeckgo/blob/master/studio/src/assets/i18n/en.json) can be translated.

Let me know if you have any other questions or observations!
