### ISSUE TITLE
studio: mock api

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#367]
To ease the local development, as long as we don't have a staging api (https://github.com/deckgo/deckdeckgo/issues/274), mock the api

**Comment by nmattia** [comment]
@peterpeterparker which API is that?

**Comment by peterpeterparker** [comment]
@nmattia our api (user(name), presentation, etc.)

**Comment by peterpeterparker** [comment]
P.S.: it will ease my development (no need to stash authentication anymore) and also will be make easier for contributors to run studio locally
