### ISSUE TITLE
studio: i18n

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#370]
## Description

The editor ("studio") is currently only available in English. Texts and codes are currently "hard coded" in the JSX files.

## Goal

Add internationalization.

## Development

What library should we use for to handle the translations? or, for challenging purpose, should we try to create our own Web Component? or could we solve that with a custom function?

**Comment by timrodz** [comment]
Here to listen about this conversation — Haven't implemented internationalisation on the web (Only games before) and am open for any ideas/suggestions.

**Comment by peterpeterparker** [comment]
coolio 👍 

I think first we should collect/list what are the solutions. Moreover than web I don't think there is yet the standard solution.

A while ago:

1. Christian wrote a tutorial https://medium.com/stencil-tricks/implementing-internationalisation-i18n-with-stencil-5e6559554117

2. @natemoo-re published https://intljs.com (did you still work and maintain it Nate?)

**Comment by mattrobineau** [comment]
> I think first we should collect/list what are the solutions.

I've also heard good things of https://www.i18next.com/.

**Comment by peterpeterparker** [comment]
thx @mattrobineau 👍

**Comment by peterpeterparker** [comment]
Another tutorial and interested approach by @sean-perkins : https://dev.to/teamhive/using-i18n-translations-within-stencil-components-4n30

I'm still a bit unclear on how we should handle translations in order to continue to be SEO friendly (what we achieve currently through a `preerendered` build of studio)

**Comment by peterpeterparker** [comment]
It seems like, according a quick test and chat on slack and finding of [Franco Vales](https://twitter.com/francoxavier33), that out of the box, as long as routes are used/declared somewhere in the app, it is possible to prerender the languages routes  with lang prefixes as for example  `https://deckdeckgo.com/en/index.html` 

<img width="1440" alt="Capture d’écran 2020-06-28 à 16 31 00" src="https://user-images.githubusercontent.com/16886711/85950517-843e6480-b95d-11ea-9863-2f8cc58b1e3e.png">

**Comment by peterpeterparker** [comment]
Just an update: I am currently working on splitting the app and website.

In this new site I'm developing with Gatsby, i18n was directly integrated. It was a major concern when I initialized the project. This means that within next weeks, it will be possible to translate most pages to any other language 🎉.

The app will follow afterwards and it will be technically easier to do so.

**Comment by peterpeterparker** [comment]
Stencil example by @jpzwarte

```
import { createStore } from '@stencil/store';
import { i18nEn } from './i18n.en';
import { i18nNl } from './i18n.nl';
import { I18n } from './i18n.interface';
const { state, onChange } = createStore<I18n>({ lang: 'en', ...i18nEn });
onChange('lang', lang => {
  let bundle: I18n;
  if (lang === 'en') {
    bundle = i18nEn;
  } else if (lang === 'nl') {
    bundle = i18nNl;
  }
  Object.assign(state, bundle);
});
export { state as i18n };
```

and then its as easy as `label={this.collapsed ? i18n.shell.expand : i18n.shell.collapse}`

**Comment by peterpeterparker** [comment]
boom done 🔥

**Comment by peterpeterparker** [comment]
@mauriciolanda4 if you are still up to translate the app in Spanish, that would be over cool and  it is now possible!!!

I wrote some lines about it in [CONTRIBUTING.md](https://github.com/deckgo/deckdeckgo/blob/master/CONTRIBUTING.md#translation). If you have any question let me know, happy to help
