### ISSUE TITLE
Add vim keybindings to control presentation

### ISSUE THREAD

**Issue by SoptikHa2** [deckgo/deckdeckgo#388]
It would be great to be able to use `j` and `k` to scroll the presentation. This could improve usability for those [25 %](https://insights.stackoverflow.com/survey/2019#technology-_-most-popular-development-environments) developers that use vim as primary IDE, and I would assume that most developers are familiar with vim keybinding, even when they don't use vim as their IDE. Vim keybindings also already work in most pdf and image viewers, so it might be a nice usability boost to this project.

**Comment by peterpeterparker** [comment]
Thx @SoptikHa2 👍 

It's a good idea and furthermore it could also be a good first issue for the hacktoberfest.

**Comment by peterpeterparker** [comment]
PR has been merged. It will be rolled out for new presentations and in our editor with the milestone `studio-beta.6`
