### ISSUE TITLE
studio: searchbar for code languages

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#389]
## Description

Currently it is not possible to filter the list of code languages. For example, when I'm looking for "JSON" I have to scroll the all list until I found it and select it.

I would be cool to add a [searchbar](https://ionicframework.com/docs/api/searchbar) to the modal where user could select the language code.

## Mockup

<img width="1259" alt="Capture d’écran 2019-10-04 à 06 42 25" src="https://user-images.githubusercontent.com/16886711/66181843-ae832000-e672-11e9-8010-6952fe7d5a28.png">
enh

**Comment by trblackw** [comment]
Hey @peterpeterparker 👋🏻 
mind if I give this a go? If so can you assign me 🤛🏻

**Comment by peterpeterparker** [comment]
Sure, awesome @trblackw 👍 

Our DB (firestore) tokens and keys are not exposed (currently) in the repo. You will need them to run "studio" (the editor) locally. Could you send me a PM? I'll then send you back these information.

P.S.: In the future we might publish in the public repo these credentials too

**Comment by trblackw** [comment]
@peterpeterparker Sounds good. I'm not familiar with a way to PM on github. Would discord work? Or email if you prefer -- tuckerblackwell.dev@gmail.com

**Comment by peterpeterparker** [comment]
@trblackw awesome, I've sent you an email 😉

**Comment by peterpeterparker** [comment]
As discussed on Slack, Paul will now try to take care of this issue

**Comment by grantlouisherman** [comment]
@peterpeterparker should I take a look?

**Comment by peterpeterparker** [comment]
that would be super cool @grantlouisherman 👍 
I think that would be a nice value for the users if that task would be solved

**Comment by grantlouisherman** [comment]
Do you want to email me the fire base stuff?

**Comment by peterpeterparker** [comment]
@grantlouisherman no need, the tokens for the test are now already contained in the repo ;)

**Comment by peterpeterparker** [comment]
```
git clone https://github.com/deckgo/deckdeckgo
cd deckdeckgo/studio
npm install
npm run start
```

and you should be good to go.

Let me know if you need further assistance!

**Comment by grantlouisherman** [comment]
Hey, @peterpeterparker I have been looking at this and I am not sure if there is a way to implement the search bar as you show it above. Just because of how the popup controllers are. The code select option is a popup controller within a popup.  I can add the search to the toolbar? Unless you know of a way to add it to the code lang options popup.

**Comment by peterpeterparker** [comment]
@grantlouisherman thank you for having a look at this. I'm agree with you, seems there is no way with the default Ionic components `ion-select`. I think the solution is then to create our own popover which should kind of look the same as the Ionic one + a filter (searchbar). I rather like a solution with the filter inside the popover, before the list of option, than an autocomplete in the toolbar.

Actually I have the same requirement in another application I'm currently developing, if you rather like, I could then take care of this?

**Comment by grantlouisherman** [comment]
hey @peterpeterparker sounds good! sorry I couldnt be more helpful. I can do the search bar functionality if you want and you can handle the placement?

**Comment by peterpeterparker** [comment]
@grantlouisherman thx for your offering. I'll begin to work on it and will see how it goes, I'll keep you posted. 

P.S.: Might take a bit before I begin this one, I'm currently battling with other issues ;)

**Comment by grantlouisherman** [comment]
@peterpeterparker totally understand. Just reach out if you need me

**Comment by peterpeterparker** [comment]
@grantlouisherman it's implemented and even unleashed in production. I went through it because it actually needed more than I thought and it was easier to do a all commit than a partial one, hope it's ok for you.

I'm happy to hear your feedback and idea of improvements as always!

Happy weekend

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16886711/73074638-5ccd0280-3eba-11ea-8457-6ae44a750f4d.gif)
