### ISSUE TITLE
inline editor: create link don't respect order

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#405]
When creating a link using the [WYSIWG inline editor](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/inline-editor) time to time the order of the sentence is not preserved

The example was in a sentence like "More about it? Something something" where something was transformed to a link. 

It seems that as "More about it?" was a text node, it was pushed at the end of the sentence once the element create "Something something More about it?"

**Comment by bokaderohit98** [comment]
@peterpeterparker  #407  check this pr

**Comment by peterpeterparker** [comment]
You are awesome @bokaderohit98 

Thx so much for the PR, it totally solves the bug 🙏
