### ISSUE TITLE
studio: add split template vertical

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#408]
### Description

In #372 a new option `vertical` was added to the `split` template. Per default this slide is still split horizontally ("two columns") with this new options it is now possible to split it vertically ("two rows").

The goal of this feature is to unleash this option in the editor ("studio")

### UX

We are not going to add an option which would allow such a slide to be transformed dynamically. I think that the implementation and the UX are going to easier if we "just" allow two different types of slide in the slide selector (see screenshot)

### Implementation

- In `slide.tsx` refactor enum `SlideTemplate` respectively `SPLIT` to `SPLIT_HORIZONTALLY` and then add a new value `SPLIT_VERTICALLY` **UPDATE: That was a bad idea, my bad**

- In `app-create-slide.tsx` add the new template

- Pass the `vertical` property till `create-slides.utils.tsx` to create effectively the slides. **PING ME ABOUT THIS** I've got something in development about that in an ongoing branch

- Add `vertical?: boolean` to `SlideAttributes` in `slide.tsx`

- In `deck-events.handler.tsx` method `getSlideAttributes` add the matching for vertical ("slide html element attribute vertical -> slide attributes object vertical variable")

- In `parse-slides.utils.tsx` method `parseSlideElement` do the contrary, object variable to html element attribute

It might be enough but it might also need some extra styling, notably if a piece of code would be added in such a vertical slide

### Screenshot

<img width="1203" alt="Capture d’écran 2019-10-13 à 13 35 36" src="https://user-images.githubusercontent.com/16886711/66715012-742a2900-edbe-11e9-8cb9-5b91c2f4ab74.png">

**Comment by timrodz** [comment]
Hey @peterpeterparker - if I may, I'd be glad to work on this. Happy to give the opportunity to someone else as well. 😃

**Comment by peterpeterparker** [comment]
@timrodz sure go for it, cool 👍

**Comment by peterpeterparker** [comment]
@timrodz to run locally studio (the editor) you will need two configuration files, ping me on slack or mail to let me give you these

**Comment by peterpeterparker** [comment]
@timrodz don't need to ping me anymore about the configurations, by pulling the last version you should be good and able to run locally the editor

**Comment by timrodz** [comment]
Working on this now! Will let you know how I go.

**Comment by timrodz** [comment]
@peterpeterparker the implementation is looking good so far. Will need to add some styling to it, though - where can I find this?

### Menu option

<img width="237" alt="Screen Shot 2019-10-20 at 1 42 18 PM" src="https://user-images.githubusercontent.com/7434353/67153066-bb289900-f33f-11e9-97a7-0592127cb1e3.png">

### Result

<img width="1419" alt="Screen Shot 2019-10-20 at 1 44 09 PM" src="https://user-images.githubusercontent.com/7434353/67153071-c085e380-f33f-11e9-8829-2aa05927b7a1.png">

**Comment by peterpeterparker** [comment]
Looks good 👍 

The style of `app-create-slide.tsx` is defined in `app-create-slide.scss`.

Note: in that popover, wrap your demo slide around the `<div class="item"/>` as the other demo slide, it should add the height and the border color

**Comment by timrodz** [comment]
Seems like the css is doubling up the size of its parent. It's wrapped around an "item" and works fine if I remove the `vertical` attribute. I might have to override something inside `deckdeckgo-slide-split.scss`

<img width="223" alt="Screen Shot 2019-10-20 at 11 08 31 PM" src="https://user-images.githubusercontent.com/7434353/67157958-8f80cf80-f38e-11e9-9052-39ea26c8f32b.png">

**Comment by peterpeterparker** [comment]
@timrodz nope, nothing to change in your cool implementation ;)

in `app-create-slide.scss` there is

```
deckgo-slide-split {
      p {
        margin: 0;
        min-height: 102px;
        overflow: hidden;
      }
    }
```

this should be modified for `vertical` split and you should be good

**Comment by timrodz** [comment]
> ```tsx
>       &[vertical] {
>         p {
>           min-height: 47px;
>         }
> ```

Thank you, I was looking for this exactly! What are those attributes called?

**Comment by peterpeterparker** [comment]
> What are those attributes called?

I don't understand your question, sorry. Could you give me a bit more context?

**Comment by timrodz** [comment]
Sure: Is there a specific word for the explaining attributes must be passed in css like `&[attribute]`?

**Comment by peterpeterparker** [comment]
No specific except `vertical` I would say. If you use 1 to 1 what I displayed above it should be good.

I quickly tried `&[vertical]` in my local environment before posting my comment, it was ok.

**Comment by peterpeterparker** [comment]
It's so cool that you created the template and even added it to the editor @timrodz 
Like you implemented the all process, really really cool 👍
