### ISSUE TITLE
feat(dashboard): add call to action "create a presentation"

### ISSUE THREAD

**Issue by KeziahMoselle** [deckgo/deckdeckgo#411]
Hi !
Awesome project !

I was testing the app and when I go to my empty dashboard I thought it would be more user-friendly to show a CTA "Create a presentation/deck" when there is no presentations at all.

Something like this (don't mind the quality of this please 😄)

![preview](https://i.imgur.com/vVEJNSQ.png)

**Comment by peterpeterparker** [comment]
Sure, excellent idea @KeziahMoselle 👍

**Comment by bokaderohit98** [comment]
@peterpeterparker  check #415

**Comment by bokaderohit98** [comment]
@peterpeterparker  doesn't #415  solve this?

**Comment by peterpeterparker** [comment]
@bokaderohit98 you are right, sorry for the delay. I just had to jump into something quickly right after the merge and didn't had time to close this this one ;)

But yes of course it does solve this, thx a lot for the PR 👍
