### ISSUE TITLE
docs: dark and light mode switcher

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#419]
in this feature I'll implement the dark and light switcher provided by @grantlouisherman in https://github.com/deckgo/deckdeckgo/issues/227 in the documentation

**Comment by grantlouisherman** [comment]
Hey @peterpeterparker let me know if you need my assistance  🤙🤙🤙

**Comment by peterpeterparker** [comment]
thx @grantlouisherman I'll! You did a great job, your code is so far self explanatory 👍

**Comment by peterpeterparker** [comment]
Done and live @grantlouisherman 😉

👉 https://docs.deckdeckgo.com
