### ISSUE TITLE
Show handles in author slide

### ISSUE THREAD

**Issue by nmattia** [deckgo/deckdeckgo#424]
Right now the author slide shows generic names for github, Twitter and other handles:

<img width="1366" alt="Screenshot 2019-10-20 at 22 59 29" src="https://user-images.githubusercontent.com/6930756/67166202-7592bd00-f38d-11e9-9d7b-077cf1745561.png">

It would be great to have `logo + handle`.

**Comment by peterpeterparker** [comment]
If I'm not wrong, the enhancement should fine place in `create-slide.utils.tsx` in method `createSocialLinks`.

Instead of slots "Twitter", "LinkedIn" etc. the related value should be use

Like 

```
<deckgo-social ...
      Twitter
</deckgo-social>
```

To 

```
<deckgo-social ...
    {user.data.social.twitter}
</deckgo-social>
```

I think...

**Comment by bokaderohit98** [comment]
@peterpeterparker  check #427. For web-url i haven't changed anything since it can be pretty long

**Comment by peterpeterparker** [comment]
@bokaderohit98 thx for the PR. actually I ask even my self now if it's a good idea because even a social username could be longer than the space available...

therefore if we do this it need also modifications in the templates "author" too

**Comment by peterpeterparker** [comment]
open to ideas

**Comment by peterpeterparker** [comment]
desktop:

<img width="1194" alt="Capture d’écran 2019-10-21 à 10 59 56" src="https://user-images.githubusercontent.com/16886711/67191476-f2578280-f3f1-11e9-9335-6a28a9e25512.png">

mobile:

<img width="1194" alt="Capture d’écran 2019-10-21 à 10 59 41" src="https://user-images.githubusercontent.com/16886711/67191491-f84d6380-f3f1-11e9-93e6-e5db63b7de35.png">

**Comment by peterpeterparker** [comment]
I'm on it. PR #556 in progress.

**Comment by peterpeterparker** [comment]
![Capture d’écran 2020-01-04 à 13 20 02](https://user-images.githubusercontent.com/16886711/71765484-d09c7080-2ef5-11ea-9de7-d9c5d3e079ca.png)

**Comment by peterpeterparker** [comment]
Done including update of the starter kit, but still need a `terraform apply` though.

@nmattia as we have still other tasks to finish, wish also will need an update of the starter kit, like the task for the fonts, I would say don't proceed with an update of the api yet, let's finish the others first.
