### ISSUE TITLE
Remote next and prev. slide not revealing items

### ISSUE THREAD

**Issue by Dellos7** [deckgo/deckdeckgo#43]
Hello @peterpeterparker, trying out today the remote control and the slides which have items that should be revealed they are not when hitting next and prev. slide from the remote control. 
It does work on the desktop, however when you just try this in the remote control it just goes directly to the actually next or previous slide, without hiding or showing the items.

Thank you for your nice work!

**Comment by peterpeterparker** [comment]
Hi @Dellos7 

Thx for the feedback, really appreciated, and thx for trying DeckDeckGo, super cool 👍 

You are totally right, that should be the case...it's just, I didn't have implemented it yet. Long story short, when I created the remote control I didn't had, at that time, the exchanged data to implement these, but it will be possible now.

You could follow the following feature request I opened end of November about it  👉 https://github.com/deckgo/deckdeckgo-app/issues/3

If you've got other ideas or see any bugs, don't hesitate to ping me 😉
David

**Comment by Dellos7** [comment]
Hello @peterpeterparker,

Thank you very much for the early response. I looked for the issues in this repo, but didn't look for them in the deckdeckgo-app one.

Right now I am preparing a presentation, so if I find out anything else I will definitely ping you. I like a lot this lot!

Regards,

David.

**Comment by peterpeterparker** [comment]
@Dellos7 awesome to hear you are trying out to build a presentation with DeckDeckGo ♥️

Ping me for any questions, ideas or bugs, it would be my pleasure to help

About issues across repo, no worries it's difficult to track them with many repo like this project. I read recently a tweet from @mlynch about the fact that the Ionic team may open source one day a tool they developed for that purpose, I keep an eye on it,  I'm super interested by such a tool
