### ISSUE TITLE
lazy-img: add width and height property

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#436]
## Description

Add new properties for width (`@Prop() imgWidth`) and height (`@Prop() imgHeight`)  of the image to the `lazy-img` component.

## Goal

Improve native lazy loading (see screenshot).

## Code

The implementation finds place in the [lazy-img](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/lazy-img) component

## Screenshot

<img width="1182" alt="Capture d’écran 2019-10-28 à 07 47 41" src="https://user-images.githubusercontent.com/16886711/67660886-ba06f580-f957-11e9-9442-06608f8c5fcd.png">

**Comment by anusha5695** [comment]
Hi @peterpeterparker : I would like to pick this

**Comment by peterpeterparker** [comment]
cool @anusha5695 go for it 👍

**Comment by peterpeterparker** [comment]
As I had to implement some improvement in the lazy-img component last week, I have added these properties at the same time: https://github.com/deckgo/deckdeckgo/pull/510
