### ISSUE TITLE
studio: dark and light mode theme switcher

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#445]
## Description

We have implemented the dark/light mode switcher in the docs and remote (not released yet), we  could now implement a dark and light theme switcher in the editor ("studio").

## Implementation

The UX implementation should follow the one of the remote (and not the docs). 

Aka

- init at startup (see remote [app-root](https://github.com/deckgo/deckdeckgo/blob/8d4229b1a82ef6dc75cb5b2a3af35c92ddf137ab/remote/src/app/app-root.tsx#L34)

- toggler in the user settings page (see remote [settings](https://github.com/deckgo/deckdeckgo/blob/master/remote/src/app/components/settings/app-general-settings/app-general-settings.tsx))

## Nota bene

The *scss* files should also be enhanced respectively the preferred scheme should be migrated to `body.dark` and new variables if mandatory

**Comment by grantlouisherman** [comment]
Hey @peterpeterparker could I take this one? Continue what I started 🤙🤙🤙🇺🇸

**Comment by peterpeterparker** [comment]
Go for it @grantlouisherman that would be awesome 👍 

Ping me if you have any questions and thx in advance!

**Comment by grantlouisherman** [comment]
Hey @peterpeterparker did you want to import the switcher from remote or create a new desired behavior for this? Usually you want to reuse the component and if it doesn't work in studio than I can try to make it more flexible.

**Comment by peterpeterparker** [comment]
I would recreate the component as the UI gonna be different.

The key point is the [service](https://github.com/deckgo/deckdeckgo/blob/master/remote/src/app/services/theme/theme.service.tsx) which we would be able to copy but I could really live with a copy of just one service, specially as in the future I don't exclude that one day the remote control will be merged in the editor to have only one app and not two.

Therefore yes go for "copy/paste".

Agree?

**Comment by grantlouisherman** [comment]
Yeah and the UI  component can be more simple because it will just be utilizing this service.

**Comment by peterpeterparker** [comment]
@grantlouisherman thx for the feedback, cool 👍 

Like in the remote, I want the option in the settings. I think it's what make the more sense.

Note: the settings "dark / light" as in the remote or the docs should be persisted only locally, not in the db

**Comment by grantlouisherman** [comment]
hey @peterpeterparker so I have a question. I have been working on this ticket and I have been battling to get the styles to traverse down the nodes. I am not sure if the shadow DOM is messing it up, but attaching .dark to the body only passes down to some of the Nodes in the DOM and I am not entirely sure why.  I accidentally updated my forks master, so I can change it after I get it working, but here is the link: https://github.com/grantlouisherman/deckdeckgo/tree/master/studio. I am not sure where I need to attach the dark class.

**Comment by peterpeterparker** [comment]
@grantlouisherman thx for the branch 👍 

I think that the style won't go through the shadowed elements that's why in such cases you would have to use css variables. but most of the editor components itself aren't shadowed, therefore they should be able to see the dark property.

- in the remote I mostly solved the dark style by defining [variables.scss](https://github.com/deckgo/deckdeckgo/blob/master/remote/src/global/theme/variables.scss#L75)

- for Ionic components which really needed a new different style, I defined a new Ionic [variable](https://github.com/deckgo/deckdeckgo/blob/2efb98f225eb9535c0384f2319349b6d1c373f41/remote/src/global/theme/variables.scss#L100)

- and when no other choice than I applied a specific style in the related non shadowed components, like

```
body.dark {
     my-component {
     }
}
```

not sure if that answer your question?

also, maybe, if you want, I could give a help?

once you have implemented for example the services, loading and settings part, you could submit a PR and I then take care of styling/applying the style across the app, team work ;)

I'll be afk today Saturday but afterwards I'll have time to help, only if you wish.

of course happy to answer any questions.

and again, thx!!!

**Comment by grantlouisherman** [comment]
Hey @peterpeterparker ill mess around with the options you gave me and if it’s still not working I’ll tap you in. Thanks for your help! 🙏🙏

**Comment by peterpeterparker** [comment]
This has been solved with PR https://github.com/deckgo/deckdeckgo/pull/501 and https://github.com/deckgo/deckdeckgo/pull/491
