### ISSUE TITLE
[Feature request] code formating

### ISSUE THREAD

**Issue by noelmace** [deckgo/deckdeckgo#470]
Adding formating using Prettier, Husky and lint-staged.

I added it to my fork with a configuration as close as possible to the existing formatting, but I had to ignore src/css/*.css and src/scripts/*.js in order to permit to ease merge from this repo master for updates.

See the following commit for an example.

**Comment by peterpeterparker** [comment]
If we add prettier we should add it to the starter but also to all components and apps, so we get a formatting across all frontend code

**Comment by peterpeterparker** [comment]
The PR #600 @StefanNieuwenhuis reminds me that we need to this.

**Comment by peterpeterparker** [comment]
Done ("mieux vaut tard que jamais") 😁

I have added prettier to all our web components and apps.

The original issue aim to add prettier to the starter kit. I think we should do it but we should also add typescript, I've opened a new separate issue for that purpose https://github.com/deckgo/deckdeckgo-starter/issues/52

Thx for the inputs 👍
