### ISSUE TITLE
publish: QR code URL 'DECKDECKGO_BASE_HREF' wasn't updated

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#490]
It was reported that when publishing a presentation from studio, the URL of a QR code, containing `DECKDECKGO_BASE_HREF` in the url, wasn't updated by the API.

As a result the QR code was pointing to an url like `https://beta.deckdeckgo.com/...../{{DECKDECKGO_BASE_HREF}}` instead of a valid url.

I should check where the problem is (studio or api?) and if I could reproduce that.

**Comment by peterpeterparker** [comment]
I could reproduce the error. In my presentation https://beta.deckdeckgo.io/daviddalbusco/issue490/ `{{DECKDECKGO_BASE_HREF}}` wasn't replaced

It should had been with https://github.com/deckgo/deckdeckgo/blob/60c88f9a7a78e5fa2182f156ec3368f20d9fb5d3/infra/handler/src/DeckGo/Handler.hs#L1275 ?

@nmattia

**Comment by peterpeterparker** [comment]
@nmattia is these changes the reason maybe?

1. https://github.com/deckgo/deckdeckgo/commit/b5aeaa458ae691aafae6ff3479187bc1aecda66e#diff-c99d0bfe3619f5766e32f3b0794e1a9c

```
T.replace "{{DECKDECKGO_BASE_HREF}}"
         ("/" <> presentationPrefix uname dname)
```

to

```
T.replace "{{DECKDECKGO_BASE_HREF}}"
    ("/" <> presentationPrefix uname pname)
```

2. then https://github.com/deckgo/deckdeckgo/commit/4001fbed33cc7059159f30520456d71aa81d26be#diff-c99d0bfe3619f5766e32f3b0794e1a9c

```
T.replace "{{DECKDECKGO_BASE_HREF}}"	
         ("/" <> presentationPrefix uname pname)
```

to

```
T.replace "{{DECKDECKGO_BASE_HREF}}"
     (presentationPrefix uname psname))
```

**Comment by nmattia** [comment]
Mh, this is really odd. Those changes only modify the text that's inserted _instead_ of `{{DECKDECKGO_BASE_HREF}}`, but either way the `{{...}}` part should be gone. Is this in index.html? is that the only `{{...}}` that fails to interpolate?

**Comment by peterpeterparker** [comment]
Yes it's in `index.html`

Yes it seems it is the only which fails

But it is also the only tag which has to be replaced and is not part of the `<head></head>`. It's an attribute of a slide.

Maybe a timing problem? Like does the replace finds place before or after the slides are parsed? If before, that's probably the reason.

**Comment by nmattia** [comment]
You're right, we first interpolate the `{{...}}`, and then add the slide content: https://github.com/deckgo/deckdeckgo/blob/7d3a1f44ebecb856e7afab10097e2830f39abb70/infra/handler/src/DeckGo/Handler.hs#L1264-L1265

This should fix it:

``` haskell
    processIndex =
      interpol . TagSoup.renderTags . processTags presentationInfo . TagSoup.parseTags
```

**Comment by peterpeterparker** [comment]
coolio 👍 

ping me to give it a try

**Comment by peterpeterparker** [comment]
Solved with https://github.com/deckgo/deckdeckgo/commit/2ddb0ee3f6d9c96fc0a8ea0983a9718ff6f40dfa

Fix is live

<img width="1264" alt="Capture d’écran 2019-12-04 à 11 33 15" src="https://user-images.githubusercontent.com/16886711/70135242-f4b42a00-1689-11ea-87f6-a7ec2b810733.png">
