### ISSUE TITLE
studio: javascript in input field

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#497]
Should we prevent Javascript in input field?

```
<h1 slot="title" spellcheck="false" >&lt;!'/*!"/*!//'/*//"/*--!&gt;&lt;Input/Autofocus/%0D*/Onfocus=alert(document.domain)//&gt;&lt;Svg&gt;</h1>
<section slot="content" spellcheck="false"  >&lt;!'/*!"/*!//'/*//"/*--!&gt;&lt;Input/Autofocus/%0D*/Onfocus=alert(document.cookie)//&gt;&lt;Svg&gt;</section>
```

**Comment by peterpeterparker** [comment]
@nmattia when you've got time, we should try to use the same CSP as in #498 in the starter kit for studio. as I can't debug or simulate, it might need (will probably need) several "terraform apply" in a row until we've got it correctly configured and working.

**Comment by peterpeterparker** [comment]
Also there is an issue linked to Stencil or Ionic which should be cleared first, see https://github.com/ionic-team/stencil/issues/2039

**Comment by nmattia** [comment]
The problem is that we can't juste du that in the client. A malicious user will most likely monitor the network, discover the API calls and upload their code directly. We should sanitize the uploaded HTML on the server.

**Comment by peterpeterparker** [comment]
In such case the code will still be blocked by a strong CSP when presentation will be displayed and therefore not executed.

**Comment by peterpeterparker** [comment]
The CSP for "studio" is ready. 

The CSP for "starter" is in a branch (https://github.com/deckgo/deckdeckgo-starter/blob/csp-studio/src/index.html#L14). With @nmattia we probably will need some iteration/retry till correctly set.

Note about sanitize: According my test, sanitize do would work but isn't sustainable as we would have to specify a explicit list of attributes which should be kept (like slot and all attributes we use for our components) and also some regex for example to not destroy the content of the slide code.

**Comment by peterpeterparker** [comment]
Done and deployed in version studio-beta.11
