### ISSUE TITLE
studio: move "deck" style (color, background) outside "slides" (accessibility)

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#520]
Currently, the deck options are accessible with the slides. If I click on a slide, through the toolbar I've got access to "color" or "image". Then in the popover I could select slide or deck.

As we "will have" to add more options related to the deck, the related options should be accessible differently. Moreover, might makes the difference between "deck and slides options" more easy to understand.

## Is

<img width="923" alt="Capture d’écran 2019-12-08 à 16 06 56" src="https://user-images.githubusercontent.com/16886711/70391404-0fadd380-19d5-11ea-912e-d82fc5c4caae.png">

## New

An "options" on the deck level to open deck related options:

<img width="1048" alt="Capture d’écran 2019-12-08 à 16 08 34" src="https://user-images.githubusercontent.com/16886711/70391406-10466a00-19d5-11ea-8dba-7f76cde9a17f.png">

The slide toolbar link to "only" slides options:

<img width="1048" alt="Capture d’écran 2019-12-08 à 16 09 41" src="https://user-images.githubusercontent.com/16886711/70391412-3ec44500-19d5-11ea-84be-4e9140ae7dbe.png">

**Comment by peterpeterparker** [comment]
As we are moving the "deck" options to a more accessible pane, we could therefore also change the "default color/background behavior".

Instead of assigning a random color to the very first slide only, when a new presentation is started, we could then assign the random color and background to the all presentation

@nmattia I guess you will be agree with this

**Comment by nmattia** [comment]
@peterpeterparker indeed I am!
