### ISSUE TITLE
feat(docs): add issue templates for issues and pull requests

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#533]
Currently there are a lot of ways people adding issues and pull requests to this repository. It's great that they contribute to this repo, but I think it's better when that can be streamlined and every issue and/or PR provides the same information.

There's this [GitHub Help article](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) about issue and pull request templates which can help in setting this up.

I think a great example of issue templates are the ones from [Angular Components](https://github.com/angular/components/tree/master/.github/ISSUE_TEMPLATE) and [Moment](https://github.com/moment/moment/tree/develop/.github/ISSUE_TEMPLATE).

**Comment by peterpeterparker** [comment]
@donroyco definitely a good idea 👍 

furthermore, as our repo is a mono-repo, providing template would probably help to narrow the issue or feature reporting.

p.s.: if you or anyone would like to contribute and provide such templates, that would be of course wonderful 😃

**Comment by donroyco** [comment]
@peterpeterparker I just put an initial PR, please have a look.

**Comment by peterpeterparker** [comment]
awesome @donroyco thx you for your PR and ideas 👍 

I just added some more components to the potential affected parts (see https://github.com/deckgo/deckdeckgo/pull/540) but for the rest it's really super!
