### ISSUE TITLE
studio: links should have different styling (to distinguish from emphasised text)

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#537]
## Current behaviour

When I came to the DeckDeckGo website for the first time, I tried to click on 'open source' and 'presentations', because on the right side I saw 'Slack', 'email' and 'Twitter' in the **exact same appearance** on the page.

<img width="817" alt="Blocks of content" src="https://user-images.githubusercontent.com/1763537/70848871-b41d9300-1e77-11ea-85e9-8dc0e5ddfc70.png"> _View of both blocks (without presentations in the middle)._

## Expected behaviour

I would expect to distinguish more easily the difference between plain, but emphasised text and clickable links.

**Comment by peterpeterparker** [comment]
Makes sense 👍 

I would say, the following should be removed from `fonts.scss`

```
strong {
  color: var(--ion-color-primary);
  font-weight: 500;
}
```

Therefore,  `strong` will be displayed as initial, black and bold

**Comment by peterpeterparker** [comment]
@donroyco we have recently printed our some stickers and we are even going to send them next week per post to our contributors.

if you are interested, drop me an email with your postal address at david.dalbusco(at)outlook.com

we would be happy to send you one too! thank you so much for your help 🙏

**Comment by donroyco** [comment]
@peterpeterparker Awesome! Let me drop you an email. 📫
