### ISSUE TITLE
Animate options

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#57]
## Description

Currently the animation is a swipe left to right in LTR or right to left in RTL.

Maybe, optionally, it would be cool to have more effects ("transition style type or swipe animation") available between slides.

Spontaneous ideas:

- a Android/md ("ionic page navigation") like animation ("slide comes from bottom")
- fade in/out
- no animation at all (update: actually I think that one is already implemented)

**Comment by TotallyNotChase** [comment]
Hey,

I noticed that there's another issue for adding another Transition. But I think that, along with any other animation you'd end up adding later on, will require a Options menu. If that's what you meant by this I can give it a try to see if I can add some options for the user to choose.

I'd appreciate it if you could give me some pointers as to where to add these options exactly and then whether you want that preference saved in a usersettings config. Please let me know!

**Comment by peterpeterparker** [comment]
@TotallyNotChase thx for reaching out 👍 

what I mean with this issue, before even adding the options and menu to the editor, is implementing the transition / effects themselves in the [core](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/core)

the current default behavior is displaying the deck as a [flex](https://github.com/deckgo/deckdeckgo/blob/cfe26f1ee4e56f5c5835b6ae9ce881feaf6c152c/webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.scss#L2) box and modifying the [transformX](https://github.com/deckgo/deckdeckgo/blob/cfe26f1ee4e56f5c5835b6ae9ce881feaf6c152c/webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx#L268) position when events occur

if we would implement new animation as options, then their particular properties should be implemented kind of the same way

Not sure my explanation is that clear, let know if you have more questions, happy to help

Screenshots from the current behavior applied:

<img width="819" alt="Capture d’écran 2019-10-06 à 09 14 03" src="https://user-images.githubusercontent.com/16886711/66265686-0197d700-e81b-11e9-9641-54be2352696e.png">
<img width="819" alt="Capture d’écran 2019-10-06 à 09 14 05" src="https://user-images.githubusercontent.com/16886711/66265687-02306d80-e81b-11e9-98bf-5188f6f31575.png">

**Comment by TotallyNotChase** [comment]
Ahh I see, I misunderstood the issue then.

So, correct me if I'm wrong, but the issue requires that the display properties be changed according to the selected animation properties right?

If so, could you give me some pointers on how should I implement this? Where should I fetch the current animation properties from and where would you like them to be implemented?

**Comment by peterpeterparker** [comment]
Yes exactly, the display properties should be changed according the animation.

Let's say per default the current ("slide dragged from left to right or right to left") animation will remains and user could for example select another type of animation (like instead of drag, fade in/ fade out).

Sorry for not being that clear, kind of difficult to explain ;)

About pointers: the implementation finds place in the core more precisely in the [deck](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/core/src/components/deck/deckdeckgo-deck) component 

I'm open to suggestion but I guess we will need a new `@Prop()` with a default value as the current animation. We could probably even reflect the prop to attribute (`@Prop({reflectToAttr: true})`) as the css would behave differently according the animation

Then, according this property, both [css](https://github.com/deckgo/deckdeckgo/blob/cfe26f1ee4e56f5c5835b6ae9ce881feaf6c152c/webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.scss#L2) and [code](https://github.com/deckgo/deckdeckgo/blob/cfe26f1ee4e56f5c5835b6ae9ce881feaf6c152c/webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx#L268) should be dynamic

Spontaneous pseudo code:

css

```
div.deckgo-deck {
    &[animation="default"] {
         display: flex;
    }

    &[animation="fade"] {
         display: ??????;
         other-property: ????;
    }
}
```

code

```
private async move(e: Event) {
      if (prop === 'default') {
         deltaX.slider.style.setProperty('--transformX', transformX + 'px');
         deltaX.slider.style.setProperty('--transformXDuration', '0ms');
     } else if (prop === 'fade') {
         somethingElse = something;
    }
}
```

But like I said, I'm open to idea and also open to animation styles. Let me know if you've got any other questions, it's cool if we do this step by step ;)

**Comment by TotallyNotChase** [comment]
I think using prop is a great idea. I want to see if I understand this correctly, forgive me for rookie mistakes, I'm very much a beginner at JS.

So should we make a new class that holds the animation value like so
```
export class newClass {
  @Prop() animation: string;
}
```

Then, set the value of this property accordingly,
```
<script>
const newClass = document.querySelector('newClass');
newClass.animation = "default";
</script>
```

Then, to handle the animation in `private async move` we can get the prop value by using the animation property and do exactly what you mentioned in the pseudo code.

Will this work?

**Comment by peterpeterparker** [comment]
@TotallyNotChase I'm not sure I understand why you would like to create a new class?

I think that the new property should be added to the main Web Component [deck core](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/core/src/components/deck/deckdeckgo-deck).

Doing so, we will be able to use the component as we already do but with a new option.

Example of usage:

```
<deckgo-deck animation="fade">
    ...
</deckgo-deck>
```

**Comment by TotallyNotChase** [comment]
Alright yeah, we can definitely add the `@Prop()` I mentioned to the `DeckdeckgoDeck` class already present in the core. 

Then we will be able to use this in the `private async move`, would that be the code framing part settled?

**Comment by peterpeterparker** [comment]
I'll implement the following transitions:

- slide (the current "slide" effect)
- none (no transition, like when I jump to a particular slide)
- fade (a brief fade effect when a slide is displayed)
