### ISSUE TITLE
docs: add Youtube video examples to doc

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#60]
## Description

I did a couple of videos about DeckDeckGo published on our Youtube channel.

It would be maybe cool to integrate them in our documentation for developers?

Youtube: https://www.youtube.com/channel/UCat0DoesaPQaR_zx9UkB2IQ
Docs: https://docs.deckdeckgo.com

**Comment by peterpeterparker** [comment]
I have generated the video and uploaded them to a Youtube channel (https://www.youtube.com/channel/UCat0DoesaPQaR_zx9UkB2IQ/featured)

**Comment by pedroapfilho** [comment]
I'll take care of this one

**Comment by peterpeterparker** [comment]
@pedroapfilho thx!

The source of the documentation finds place in the markdown files (https://github.com/deckgo/deckdeckgo/tree/master/docs/docs).

Note: there is currently no live reload. the markdown content is transformed and injected into the tsx file when the start or build run. what you could do is running npm run start and if you want to generate the doc again after some changes, run a npm run build in another command line

Ping me if you've got questions
