### ISSUE TITLE
studio(meta): tag info may be updated 

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#603]
### Affected part of DeckDeckGo
- [x] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

### Reproduction

Steps to reproduce:
1. Go to https://deckdeckgo.com/ and view source or:
1. Go to https://metatags.io/ and fill https://deckdeckgo.com/ in the URL
2. Look at the different appearances for sharing on platforms 
 
### Expected Behavior

To see directly what DeckDeckGo is about:
- Tag `title` with explanation: _DeckDeckGo - The open source web editor for presentations_
- Meta description update
- Image update with correct dimensions (1200x628)

Possible solution (Google)
<img width="631" alt="Google search result for DeckDeckGo" src="https://user-images.githubusercontent.com/1763537/73126051-2b356380-3fae-11ea-8187-06f97300657b.png">

### Actual Behavior

Current info is very brief.

Current solution (Google)
<img width="458" alt="Google search result for DeckDeckGo" src="https://user-images.githubusercontent.com/1763537/73126060-50c26d00-3fae-11ea-895e-e3f90bfd98f1.png">
This shows an updated title and description.

The current social share image is linking to the Android icon:
```html
<meta property=og:image content="https://deckdeckgo.com/assets/favicon/android-chrome-512x512.png">
```

Therefore, the implementation for Twitter looks a bit stretched.
<img width="546" alt="Twitter share result for DeckDeckGo" src="https://user-images.githubusercontent.com/1763537/73126103-fbd32680-3fae-11ea-98cb-94238b4e37af.png">
 

### Environment

- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

**Comment by peterpeterparker** [comment]
My gosh yes, we should have done that a long time ago!

Done and live, thx for the input @donroyco 👍 

Ping me if you think it still need improvements

**Comment by donroyco** [comment]
@peterpeterparker This looks like how it should have been. Thank you!

**Comment by peterpeterparker** [comment]
Awesome thanks a lot for the feedback, happy to hear that 😃
