### ISSUE TITLE
starter: jump to slide prevented by CSP

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#609]
### Affected part of DeckDeckGo
- [X] Starter kit

### Reproduction
"Jump to slide" in the starter kit doesn't work anymore as inline script is prevented by the CSP policy

See screenshot.
 
 
### Expected Behavior

No inline script ;)

### Screenshot

<img width="1496" alt="screenshot_2020-02-08_at_11 20 50" src="https://user-images.githubusercontent.com/16886711/74083799-48673900-4a68-11ea-88a7-309d61234300.png">

**Comment by peterpeterparker** [comment]
@nmattia it need a "terraform apply" to unleash the fix (it's in the stater)

**Comment by nmattia** [comment]
@peterpeterparker done, pushed to master!
