### ISSUE TITLE
Integration of MathJax

### ISSUE THREAD

**Issue by pattacini** [deckgo/deckdeckgo#622]
### Affected part of DeckDeckGo
- [ ] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [X] Web Components
- [ ] Templates
 
### Feature Description
It would be super nice to integrate [MathJax ](https://www.mathjax.org) (or some equivalent components like KaTeX) into DeckDeckGo.

### Use Case
This way, we could show complicated mathematical expressions without taking the snapshots of the formulae as pictures.

This feature would work as a quite important enabler for those of us doing scientific presentations.

Note that competitors like [Marp](https://marp.app) already sport such an integration.

**Comment by peterpeterparker** [comment]
That's a freaking cool idea @pattacini 

In terms of implementation, I could think that it would be something similar to our existing implementation for code highlighting. A web component to wrap the user interaction and the math library underneath. Then use we could offer the component for the developers and integrate it in the editor (studio) too. Definitely sounds feasible and maybe even something where we don't have to begin from scratch.

That being said, I had a look at MathJax and it does seems to be proprietary, is that correct?

For that reason, open source is a must, on a first quick look, seem that KaTex or Map, would be a better match. 

P.S.:  I ping @nmattia I'm pretty sure he gonna like this ;)

**Comment by pattacini** [comment]
It's definitely great that you're loving the idea @peterpeterparker 👍 

I'm not into MathJax; it's just the first solution I know that's come to my mind. It's being used in StackOverflow for example.

Other alternatives are totally fine.

**Comment by peterpeterparker** [comment]
Super 👍

We are currently working on a quite big other feature but I'll definitely have a look deeper at this asap

Or if anyone is willing to contribute to this, that would be awesome 😉

Thx again for the idea!

**Comment by boradakash** [comment]
Hey, Can I try this out?

**Comment by peterpeterparker** [comment]
Thx @boradakash for the awesome PR 👍

**Comment by pattacini** [comment]
Great! Thanks!

**Comment by peterpeterparker** [comment]
@pattacini thx you for the great idea!

p.s.: it is not yet  deployed in our online editor, we have to rollout the cloud first but hopefully soon

will [tweet](https://twitter.com/) about it when done :)
