### ISSUE TITLE
docs.deckdeckgo.com doesn't show 404

### ISSUE THREAD

**Issue by nmattia** [deckgo/deckdeckgo#652]
### Affected part of DeckDeckGo
- [ ] Studio
- [ ] Remote control
- [x] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

Looks like the [documentation website](https://docs.deckdeckgo.com/) doesn't return a 404 if a page doesn't exist. Instead, it just shows an empty page:

https://docs.deckdeckgo.com/components/foo-bar-baz

**Comment by peterpeterparker** [comment]
Linked with a known Ionic open feature request, see https://github.com/ionic-team/ionic/issues/18687

**Comment by peterpeterparker** [comment]
1.5 years later, solved 😉. a must for next version as I modified and deleted some routes of studio.
