### ISSUE TITLE
DRR rotation miscalculated on first click 

### ISSUE THREAD

**Issue by ble** [deckgo/deckdeckgo#655]
### Affected part of DeckDeckGo
- [ ] Web Components (DRR)

### Reproduction

Steps to reproduce:
1. Visit https://docs.deckdeckgo.com/components/drr/
2. Resize element to have large width, small height: ![image](https://user-images.githubusercontent.com/536767/75813370-e3002280-5d5d-11ea-857c-d71e34ff0ee4.png)
3. Rotate element so that the rotation handle is nearly 90 or 270 degrees from horizontal: 
![image](https://user-images.githubusercontent.com/536767/75813438-ff9c5a80-5d5d-11ea-8d90-d87b99723793.png)
4. Click the rotation handle and attempt to rotate it a short distance (by dragging the handle a short distance)
5. Observe a large jump in rotation: 
![image](https://user-images.githubusercontent.com/536767/75813578-37a39d80-5d5e-11ea-9d21-c8f4e98894b1.png)

 
 
### Expected Behavior

The element should rotate a small amount, continuously with the motion of the mouse.

### Actual Behavior

On the first rotation, the element's rotation angle jumps significantly.

### Environment

- Browser(s): Chrome Canary - Version 82.0.4069.0 (Official Build) canary (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by ble** [comment]
I believe that these two lines are the issue:
https://github.com/deckgo/deckdeckgo/blob/267b16dd8ceedcdb92789a3cd98fdc059720fc6f/webcomponents/drag-resize-rotate/src/components/deckdeckgo-drr.tsx#L217-L218

At least in this browser, Element.offsetWidth and Element.offsetHeight do not appear to account for the rotation of the element.

**Comment by ble** [comment]
I was able to test a fix for this issue by setting a breakpoint in the above code (after prettifying it in the Web Inspector) and then, when paused at that breakpoint, running:

```
this.__proto__.initStartPositionsRotation = function() {
  let rect = this.el.getBoundingClientRect();
  this.centerX = rect.left + rect.width / 2;
  this.centerY = rect.top + rect.height / 2;
 
}
```
after which the (monkeypatched) DRR no longer exhibited any signs of jumping on first rotation.

**Comment by peterpeterparker** [comment]
@ble sweet! let me try quickly

**Comment by peterpeterparker** [comment]
Yes @ble absolutely that solve the issue!!! I tested both the component in standalone mode and integrate locally in the documentation, it works like a charm.

Would you like to provide a PR?

**Comment by ble** [comment]
yeah, let me see if i can remember how to do it :)))

**Comment by peterpeterparker** [comment]
awesome

**Comment by ble** [comment]
https://github.com/deckgo/deckdeckgo/pull/656 hmm, maybe this will auto-associate them?

**Comment by peterpeterparker** [comment]
a new version of component is published in npm, docs and remote are updated and have been deployed (might need a good browser refresh) 🎉

in the editor, fix will be unleashed in next major release 

really awesome! thx again @ble
