### ISSUE TITLE
remote: drawing circle clear the all pane

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#66]
## Description

When I remote control a presentation using the remote app and when I'm drawing over my presentation, if I draw a circle it will clear the all pane.

I didn't found a solution to draw "dragging circle" on touchmove without clearing the all pane.

It should be possible to draw many circles, that would be cooler.

**Comment by janscheidegger** [comment]
@peterpeterparker I think we need to save all existing objects in a list or somehow to achieve this. I could tackle this in the afternoon.

**Comment by peterpeterparker** [comment]
@janscheidegger that would be super cool, thx in advance for any inputs 👍 keep me posted

**Comment by peterpeterparker** [comment]
Remote component has been released. The remote control app part will bee released once the rework of the UX done (see #228)
