### ISSUE TITLE
studio(a11y): two H1 headings on settings page

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#671]
### Affected part of DeckDeckGo
- [x] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

### Reproduction

Steps to reproduce:
1. Go to https://deckdeckgo.com/settings
2. Look at rendered HTML
  
### Expected Behavior

I expect to see only one H1 heading in `<main>`, as advised by HTML standards. You can have multiple H1 across a page, but then it's in different parts and tags. I expect the second H1 to be an H2 element.

### Actual Behavior

Two headings have the same H1 heading. I checked it with the [Accessibility Insights for Web extension](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni) on Google Chrome.

<img width="1043" alt="Screenshot of settings page with two H1 headings" src="https://user-images.githubusercontent.com/1763537/77223735-87a4a180-6b5f-11ea-9c9f-8062a2da7d8f.png">

_Screenshot of settings page with two H1 headings_

The documentation for headings from Accessibility Insights for Web also advises it:
> **Use only one top-level heading.**
> Top-level (h1) headings should give an overall description of the page content.
> Top-level (h1) headings can be similar, or even identical, to the page title.

### Environment

- Browser(s): Chrome, latest version
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by peterpeterparker** [comment]
Well spotted @donroyco !

I would even say that the second heading doesn't make sense, my bad. Therefore I removed it, no heading, no problem ;)

Thx for the issue 👍 

Stay safe!

**Comment by donroyco** [comment]
Thanks for the quick followup David! Take care and stay safe! 🙏🏻
