### ISSUE TITLE
template: split vertical text alignment

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#679]
### Affected part of DeckDeckGo
- [X] Templates
 
### Feature Description

Currently the template `split` display the text centered in mode both rows or columns.

In case of two columns text would be easier to read if left aligned respectively right if LTR

See screenshots.

Therefore this task has for goal to change the default alignment if two columns.

### Note

This might not be a template issue but rather a feature to develop in the common css for decks shared across starter kits and studio

### Screenshots

<img width="1319" alt="Capture d’écran 2020-03-28 à 13 13 02" src="https://user-images.githubusercontent.com/16886711/77822813-62330d00-70f6-11ea-9241-d5de6cc578ea.png">
<img width="1319" alt="Capture d’écran 2020-03-28 à 13 13 19" src="https://user-images.githubusercontent.com/16886711/77822815-63fcd080-70f6-11ea-81d0-359ac0fb733b.png">
m

**Comment by boradakash** [comment]
I'll give it a try on this.
Can you assign me?

**Comment by peterpeterparker** [comment]
@boradakash awesome 👍

**Comment by peterpeterparker** [comment]
@boradakash did you already began to work on this?

just noticed that it is maybe already implemented in the template itself (`--slide-split-text-align: center;`) means it has to be modified somewhere else...I've to search

**Comment by boradakash** [comment]
I've asked you related question on slack. There's a css change in utils project.

**Comment by peterpeterparker** [comment]
Coolio, gonna answer you on Slack ;)

**Comment by peterpeterparker** [comment]
PR  #693 provided by @boradakash is merged.

The util still need to be published to npm and rolled out in our apps. We will take care of this when we will release next version as it has to be synchronized with the starter kit too

**Comment by peterpeterparker** [comment]
Done. We just need to deploy.
