### ISSUE TITLE
inline-editor: add a feature for text aligment

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#680]
### Affected part of DeckDeckGo
- [X ] Studio
 
### Feature Description

Add a feature to studio to let user modify the text alignment (left, center and right) for the titles and paragraphs elements.

This can be solved by improving the [inline-editor](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/inline-editor) component.

Three options Left/Center/Right alignment icons will be put after Bold/Italic/Underline.

It should also detect the current setting to highlight it on opening.

Special note: We should test out the aspect ratio on small devices and mobile as it uses the sticky option.

**Comment by boradakash** [comment]
Hey @peterpeterparker 
I would like to give it try on this.
Can you assign me this task?

Thanks

**Comment by peterpeterparker** [comment]
@boradakash sweet 👍
