### ISSUE TITLE
feat: migrate to Workbox v5

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#691]
### Affected part of DeckDeckGo
- [X] Studio

 ### Feature Description

We are using Workbox v4.3.1, it would be cool to migrate our editor to Workbox v5.

 ### What to do

- upgrade [studio](https://github.com/deckgo/deckdeckgo/tree/master/studio), our editor, to the last version of Workbox

- migrate the script [sw.js](https://github.com/deckgo/deckdeckgo/tree/master/studio/src/sw.js) to match the changes of Workbox v5. This script contains some logic to support the offline mode, therefore it should be updated with attention.

### Test

Out of the box, it is not possible to run a productive build of studio as we  don't expose our productive configuration. To overcome this issue you can fake its config  as following (in studio's root):

```
cp config.dev.json config.staging.json
cp config.dev.json config.prod.json
cp src/assetlinks.dev.json src/assetlinks.prod.json
```

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by achimoraites** [comment]
Hello @peterpeterparker !
This looks interesting can i take it ?

**Comment by peterpeterparker** [comment]
@achimoraites I would love help on that one, go for it and thx!!!
