### ISSUE TITLE
[core] Transition animation with "fade effect"

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#70]
## Description

Currently the transition between slide occurs through a "swipe animation" (right to left or left to right in RTL).

It would be cool to have optionally an other transition effect respectively to be able to set the animation as a "fade effect" between slides.

## Tech info

This feature should be implement in the `/webcomponents/core/` components of DeckDeckGo. It needs probably a bit of CSS and the [transform](https://github.com/deckgo/deckdeckgo/blob/fe9033fa83387feb34eb1d85ec535534ecc6fbd0/webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx#L258) property should be handled differently.

## Get started

Interested to get involved and to try to implement this feature? Ping me if you have any questions or need help to get started, David (@peterpeterparker or [twitter.com/daviddalbusco](https://twitter.com/daviddalbusco)) 😃

**Comment by peterpeterparker** [comment]
The current "slide" effect

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16886711/61940812-83a38e00-af96-11e9-870e-40a0db7e4311.gif)

**Comment by perceptron007** [comment]
@peterpeterparker I would like to help you out on this issue. Can you give me a few pointers where should I start?
Also, I am going to take a look at the codebase for getting familiar but would be helpful if you can tell me what exactly needed to be done.

**Comment by peterpeterparker** [comment]
cool @perceptron007  👍 

This feature should be implemented in our [core](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/core) web components

Important: all our components should remains as much as possible agnostic, therefore it should be implemented without adding any dependencies, it's more fun ;)

About where to start, you could have a look at the current [move transform](https://github.com/deckgo/deckdeckgo/blob/fe9033fa83387feb34eb1d85ec535534ecc6fbd0/webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx#L258) function. I guess that once a new option added, if this option is set, the transform should not be performed that way and instead the "fade effect" should occurs

Likewise probably, if the option is set, nothing should happens when the slide is [moved](https://github.com/deckgo/deckdeckgo/blob/fe9033fa83387feb34eb1d85ec535534ecc6fbd0/webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx#L210)

Let me know if you need more info

**Comment by peterpeterparker** [comment]
Duplicate #57
