### ISSUE TITLE
studio: more list style

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#705]
### Affected part of DeckDeckGo
- [X] Studio
 
### Feature Description

Currently we support "ordered" and "unordered" list. It would be may cool to support more style.

I can think on "checkmark" for example.

This feature has to developed in our [editor](https://github.com/deckgo/deckdeckgo/tree/master/studio).

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

### Screenshot

<img width="1287" alt="Capture d’écran 2020-09-26 à 09 52 37" src="https://user-images.githubusercontent.com/16886711/94335769-164a1d80-ffde-11ea-8450-191f0c6493ff.png">

**Comment by TheIllusionistMirage** [comment]
Hi @peterpeterparker , I would like to work on this issue.
