### ISSUE TITLE
Transform white-space to a CSS in deckdeckgo/highlight-code

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#707]
### Affected part of DeckDeckGo
- [X] Web Components
 
### Feature Description

Request provided by @williamkwao in https://github.com/deckgo/gatsby-remark-highlight-code/issues/7

Another feature that I think will be nice to have is the ability to pass a CSS or config var that will enable library users to set the white-space property of the code block in the shadow dom. The code currently wraps and I'll prefer it to have a horizontal scroll. I know this one might require a some changes in @deckdeckgo/highlight-code web component.

**Comment by williamkwao** [comment]
Thanks, @peterpeterparker! I'll start working on this.

**Comment by peterpeterparker** [comment]
Sweet @williamkwao 👍 

Ping me if you have any questions

**Comment by peterpeterparker** [comment]
PS.: The component is there in our monorepo -> https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/highlight-code

**Comment by peterpeterparker** [comment]
Nice!

I have released a new version of both the component and the related Gatsby plugin, doing so your two PRs should be now available.

Thx a lot @williamkwao 👍

**Comment by williamkwao** [comment]
Thanks! Will definitely look for more opportunities to contribute
