### ISSUE TITLE
highlight-code: carbon theming

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#733]
### Affected part of DeckDeckGo
- [X] Web Components
 
### Feature Description

The [highlight-code](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/highlight-code) component has three display modes: `carbon`, `ubuntu` and `none`.

Carbon is of course inspired from the amazing [https://carbon.now.sh/](https://carbon.now.sh/).

The current style looks like the `Dracula` and I think it would be cool to have more theming options.

```
<deckgo-higlight-code terminal='carbon' theme='cobalt'/>
```

### Goal

Add `themes` to the `higlight-code` component if `terminal` is `carbon`

### Question

Open to discussion about the solutions. Should we implement the `themes` directly in the component or should we provide theses as an add-ons library?

If add-ons library, we already got a default we already got a [utils](https://github.com/deckgo/deckdeckgo/tree/master/utils/deck) which support sass, css minification etc. We can use this library structure to create a new one.

### Studio Integration

This issue has no other goal than the themin. The "studio" (our editor) integration will be implemented afterwards in a separate issue.

### Use cases

Moreover than our presentations, this component is also used in our [gatsby](https://github.com/deckgo/gatsby-remark-highlight-code) plugin. Therefore this improvements might be profitable for many use cases.

**Comment by boradakash** [comment]
Can you assign this to me?
I'll give a try on it

**Comment by peterpeterparker** [comment]
@boradakash coolio! sure

**Comment by boradakash** [comment]
Well, I think we should add themes inside the component project.
Because I don't think that theming style will be re-used anywhere else as it's part of the highlight-code only.

**Comment by peterpeterparker** [comment]
Yes not reuse anywhere else but more performant if only fetched if needed.

Let's do like that. First we add the themes inside the component and let's see afterwards what we do. Might also be easier to implement if done inside.

**Comment by peterpeterparker** [comment]
@boradakash thx for the PR 👍 

the component  has been released and integrated in our starter kit.
it has also been integrated to studio (but not yet released) and I'll take care of the  gatsby plugin after a short run ;)
