### ISSUE TITLE
Share doesn't work in Firefox, RegExp issue

### ISSUE THREAD

**Issue by Eccenux** [deckgo/deckdeckgo#751]
### Affected part of DeckDeckGo
- [x] Studio
- [x] Demo

### Reproduction

Steps to reproduce:
1. Login
2. Type something in the title.
3. Click "Ready to share?"
 
 
### Expected Behavior

Use standard RegExp like `[\s\S]` if you want to match anything.

### Actual Behavior

```
SyntaxError: invalid regular expression flag s
p-1lbwegin.entry.js:1:6550
TypeError: i is undefined
p-35791482.js:1:13935
```

Note that `s` flag is not supported in FF. Not sure why would you need one in a share button 😉.

### Environment

- Browser(s):  Firefox 76
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by peterpeterparker** [comment]
Thx for the isse @Eccenux 

It is solved and I've deployed a hot fix.
