### ISSUE TITLE
starter: mardkown support v2

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#760]
### Affected part of DeckDeckGo
- [X] Starter kit
 
### Feature Description

Our first language is HTML. The [markdown](https://github.com/deckgo/deckdeckgo/tree/master/webpack/src/markdown) converts MD to Html.

Even though it does the job, it would need some love and I think it can definitely be improved, a lot.

If anyone is interested to improve this markdown support, and probably even rewrite it from scratch to make it  better, it would be awesome!

### Current concept

You always begin a slit with `---` and then specify the name. For example, if `deckgo-slide-title` then you do `---title`.

On the same line, you can pass the slides attributes as you would do in html like `fullscreen="true"`

Then the markdown parser will try to match what's follow with the typical slots available in the templates like the first title # My title will be match to `<h1 slot="title"/>`

### Future concept

I'm open to suggestion - let me know how you would rewrite from scatch the markdown support for our [starter-kit](https://github.com/deckgo/starter-kit)

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by Justobioma** [comment]
Hi @peterpeterparker 
I would love to help. I am shooting you an email right away.
Cheers
Regards
@justobioma

**Comment by peterpeterparker** [comment]
Awesome!

**Comment by Justobioma** [comment]
Hi David,
How are you doing?
I just want to be double sure. The two documents I need to rewrite are CHANGELOG.md and README.md.
I have them on my local machine now and ready to kick off!

Obioma

​

Obioma Osuagwu
Lagos, Nigeria

________________________________

**Comment by peterpeterparker** [comment]
Hi Obioma,

I am fine and what about you?

Actually no, that is not the goal of the issue.

The goal is to create a fully new Makdown parser which should transform the presentations written in Markdown to HTML.
This should probably be developed by writing a all new Webpack Plugin.

Would that works for you?

Best regards
David

**Comment by Justobioma** [comment]
Ok. Thanks for the clarification.Much clearer now.I will work on that now.ObiomaOn 26 Sep 2020 7:11 PM, David Dal Busco <notifications@github.com> wrote:

Hi Obioma,



I am fine and what about you?



Actually no, that is not the goal of the issue.



The goal is to create a fully new Makdown parser which should transform the presentations written in Markdown to HTML.

This should probably be developed by writing a all new Webpack Plugin.



Would that works for you?



Best regards

David

**Comment by peterpeterparker** [comment]
@Justobioma nice! let me know what's your concept, looking forward to hear about it.

**Comment by Justobioma** [comment]
Sure, I will keep you updated on this.


Obioma


________________________________

**Comment by Justobioma** [comment]
Hi David,My plan is to build the parser using Regular expressions with JavaScript.I hope this falls in line with your methodologies.Let me know please.ObiomaOn 26 Sep 2020 8:31 PM, Obioma Osuagwu <justobioma@outlook.com> wrote:


Sure, I will keep you updated on this.








Obioma

**Comment by peterpeterparker** [comment]
Hi @Justobioma,

Thx for the answer. Beside the technical part I am more  interested in the concept.

Let's say a use start a presentation with our CLI (`npm init deckdeckgo`) and select MARKDOWN.

Now, he/she is about to  write his/her first slide in `index.md`, what does he/she enter? what code?

Concretely, let's say the [title](https://docs.deckdeckgo.com/slides/title) template would be use, what should be entered?

As I said in the description, I find the current mechanism not super. I can imagine that it would be better with some sort of being able to comments. Maybe something like

```
/**
* template: title
* attributes:
*    something: blue
* style:
*    --background: red
*
*/

/* slot title */

My text

etc.
```

Just  a  spontaneous idea but cleaner.

Maybe we can also think if Mdx can be used / integrated for such purpose ?

So yes, before developing anything, let's clear up the concept and format, what do you think?

**Comment by Justobioma** [comment]
Thanks David,

This is becoming clearer by the day. Let me get back to you soon on this. I think I have to dive in deeper to understand better.

Cheers

​

Obioma Osuagwu
Lagos, Nigeria

________________________________

**Comment by Justobioma** [comment]
Hi @peterpeterparker 
I don't know if I make any sense in my response here but see if you can discern what I am trying to pass on;
Here are my observations in starting off using npm...
1. This launches a read-only page with gibberish on http://localhost:3333/. One can't
seem to do anything from there
2. Node version error - The current version is 12.18.4. It asks for V14.5.0. Is this futuristic?
   However, on docs.deckdeckgo.com/docs, version 10 or higher is recommended.
3. Sure you would need to make selection in form of comments which should hold such
information as the properties of the slide as you listed earlier.
4. Sure mdx looks like a good candidate to fix this.
5. The user needs to have a .md editor installed on his/her machine to work on the slides

I can't seem to wrap my head over how to fix this now but I can start with the following;
1. Let the slide be a clean slate once I launch on http://localhost:3333/
2. Then let the slide be exportable to a popular format like .jpg/.pdf/.docx

**Comment by peterpeterparker** [comment]
Hi  @Justobioma  thank you for your time and feedback

I notice something interesting in the fact that you think too that mdx might  be an interesting direction but, I am  not sure I understand why  and how you landed on  a localhost `3333`  port which is commonly  a  Stencil dev server and not  related  to this issue.

Again, before doing and developing anything regarding this feature  request, it should be defined what is the concept and  format which we would  like  to use for the starter kit markdown  aka what users would have to enter if they want to create their presentation using markdown only.

Feel like maybe we are both going  in two direction here, is that possible?

Maybe I should assign me back the issue and take some times  to describe better what are the  goals, current status etc. etc.?

**Comment by Justobioma** [comment]
Thanks for the response.
I actually  landed on the localhost 3333 port on running the following command on my cli and choosing "markdown"
>> npm init deckdeckgo
From my observation, this is only present from the cli.
Maybe I fail to grasp completely what is expected here.
Please feel free to do what you think is the best option required to fix this issue.

**Comment by peterpeterparker** [comment]
@Justobioma thx for the feedback, that's actually  pretty strange 🤔

I don't want you to invest too much time, I need to refine this story and feature request  to make things more clear.

If you are ok, I would say let's put  this on hold / stop,  my job now to make things clearer.

Thanks for your feedback, it helps focus the feature!

Of course, if you are up  to pick any other hacktoberfest feature your are most than welcome. Thank you for your  help.

**Comment by peterpeterparker** [comment]
After much thinking about it, I'll deprecate the developer-kit markdown (in https://github.com/deckgo/deckdeckgo/issues/975) as the solution is not awesome.

If anyone would be  interested to developed it  from the ground, let me know.
