### ISSUE TITLE
studio(a11y): add warning when colors do not meet contrast ratio

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#819]
### Affected part of DeckDeckGo
- [x] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

 
### Feature Description

When using the editor, a warning could be shown when the foreground color compared to its background color do not meet contrast ratio WCAG 2.0 requirements.

Resources:
- [WebAIM](https://webaim.org/resources/contrastchecker/)
- [Building your own color contrast checker](https://dev.to/alvaromontoro/building-your-own-color-contrast-checker-4j7o)
- [Color contrast - Accessibility MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast)

It would be nice to show it next to the editor context menu and/or in the sidebar, so customers can quickly alter colors.

<img width="411" alt="Screenshot 2020-07-28 at 19 12 54" src="https://user-images.githubusercontent.com/1763537/88709800-f3060d80-d115-11ea-88c3-95040abda8bf.png">

### Use Case

When *giving* a presentation, everyone in the room should see the slides correctly, even if they have some slight visual problem. It would be nice to give a heads up when *building* the presentation, so everyone can participate during the presentation.

**Comment by peterpeterparker** [comment]
I love the idea!

Don't know how technically (yet), specially when the deck's or slide's background is an image, neither how to make this shine in terms of design, but I really like the idea and definitely see the asset here!

Thx for sharing 👍

**Comment by peterpeterparker** [comment]
thank you for the excellent idea @donroyco !!!

it will be (soon) released with v2.2.0 :)
