### ISSUE TITLE
studio(a11y): toolbar options skips some options

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#821]
### Affected part of DeckDeckGo
- [x] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

### Reproduction

Steps to reproduce:
1. Go to editor
2. Add one element (so you have Deck > Slide > Element).
3. Enable VoiceOver (macOS).
4. Navigate back to Deck
5. Try to reach **Add Slide** or **Style**  in toolbar with keyboard navigation only.
 
### Expected Behavior

To be able to reach the toolbar options.

### Actual Behavior

Not able able to reach toolbar options Add Slide or Style.

![20200730-a11y-issue](https://user-images.githubusercontent.com/1763537/88943427-beb45d80-d28b-11ea-8afa-636d325dcf20.gif)

(I think it's because `<app-action-busy>` wraps around the option button). It might be related to changes in #536 

### Environment

- Browser(s): Chrome, latest version
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by peterpeterparker** [comment]
Because you are highlighting `<app-action-busy>` I spontaneously think that it might be a side effect of removing and migrating from rxjs to the stencil store. Maybe because of that, the "event / state" is not well handled and therefore the slide step remain disabled.

I have to check. In any case, well spotted and thank you for opening the issue!

**Comment by peterpeterparker** [comment]
Mmmmh it actually worked out for me 🤔

<img width="1440" alt="Capture d’écran 2020-07-31 à 16 09 06" src="https://user-images.githubusercontent.com/16886711/89043090-4495de80-d348-11ea-9f64-a54b048f1a4c.png">

**Comment by donroyco** [comment]
@peterpeterparker It's about the toolbar options, not the breadcrumbs

**Comment by peterpeterparker** [comment]
oh I see thx. there is also the issue (if slide or elements are selected) that the button are now remove but "hidden" and still in the tab list

<img width="1440" alt="Capture d’écran 2020-08-01 à 14 29 56" src="https://user-images.githubusercontent.com/16886711/89101782-9cdde680-d403-11ea-9258-189379f13890.png">

**Comment by peterpeterparker** [comment]
Oh, I actually solved that on in https://github.com/deckgo/deckdeckgo/pull/832 :)
