### ISSUE TITLE
error on running npm run start on deckdeckgo/studio

### ISSUE THREAD

**Issue by Zegoverno** [deckgo/deckdeckgo#825]
Error: Package exports for '/Users/zegov/workspace/deckdeckgo/studio/node_modules/colorette' do not define a
           valid '.' target at resolveExportsTarget (internal/modules/cjs/loader.js:545:13) at applyExports
           (internal/modules/cjs/loader.js:459:14) at resolveExports (internal/modules/cjs/loader.js:508:12) at
           Function.Module._findPath (internal/modules/cjs/loader.js:577:20) at Function.Module._resolveFilename
           (internal/modules/cjs/loader.js:879:27) at Function.Module._load (internal/modules/cjs/loader.js:785:27) at
           Module.require (internal/modules/cjs/loader.js:956:19) at require (internal/modules/cjs/helpers.js:74:18) at
           Object.<anonymous>
           (/Users/zegov/workspace/deckdeckgo/studio/node_modules/autoprefixer/lib/autoprefixer.js:5:17) at
           Module._compile (internal/modules/cjs/loader.js:1063:30)

**Comment by peterpeterparker** [comment]
I can't reproduce the issue. If you think there is indeed one, please provide more details, thx in advance.
