### ISSUE TITLE
Cannot read property 'tokenizePlaceholders' of undefined 

### ISSUE THREAD

**Issue by yuchanns** [deckgo/deckdeckgo#848]
Related issue https://github.com/PrismJS/prism/issues/1395

Cannot highlight code language php since `The dependency for PHP has changed`.

Solution: `include the component markup-templating in addition`.

**Comment by peterpeterparker** [comment]
Thx for the issue, you are right, for languages as PHP, other dependencies  have to be loaded on the fly.

I should try  fetch  the [definition](https://github.com/PrismJS/prism/blob/5c33f0bbcf77b468b2f2b5944c9a9f04342c0bae/plugins/autoloader/prism-autoloader.js#L11) before or at build time of our WC and use  it to download on the fly what's needed.

**Comment by peterpeterparker** [comment]
the issue has been solved and the web component has been spread in all our apps and in the gatsby plugin for which I published a new version/fix too.

thx for the issue @yuchanns 👍
