### ISSUE TITLE
studio: display regions in services list

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#856]
### Affected part of DeckDeckGo
- [X] Studio

### Feature Description

Moreover than listing the services we are using on a dedicated page (https://deckdeckgo.com/services), we should also, in order to be even more transparent, display in which region we do have set our clouds.

### What to do

Add / display the location of the clouds  on the [services](https://deckdeckgo.com/services) page.

The source page to modify is available in studio: https://github.com/deckgo/deckdeckgo/tree/master/studio/src/app/pages/core/about/app-services 

### Locations

Firebase is set in "nam5 (us-central)"

AWS is set in "us-east-1 (Virginia)"

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by nmattia** [comment]
AWS is us-east-1 (Virginia)

**Comment by hjades** [comment]
hey! can i pick this up for hacktoberfest? thanks~ 😃

**Comment by peterpeterparker** [comment]
Sure, awesome! Thx @hjades 🙏

**Comment by peterpeterparker** [comment]
If you would you like to get some DeckDeckGo stickers @hjades, send me your address through pm if interested.
