### ISSUE TITLE
API crash on unique constraint

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#859]
### Affected part of DeckDeckGo
- [X] API

### Reproduction

Steps to reproduce:

1. Sign in in Studio with a brand new user, as for example `nicolas.hello@gmail.com` (note the domain name)
2. Within the logging, the API will generate a new **username** for the user as for example `nicolas`

3. Sign out

4. Sign in in Studio with another new user, having the same email prefix but another domain, as for example `nicolas.hello@outlook.com` (note the different domain name but same email prefix)
5.  Within the logging, the API will generate a new username **identical** as the previous one, for example `nicolas`, and therefore will generate a duplicate key value  which violates the unique constraint

**Comment by nmattia** [comment]
Fixed in a039ce921fd40acbc5aa986101f1c30314549053
