### ISSUE TITLE
studio: border-radius

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#865]
### Affected part of DeckDeckGo
- [X] Studio

### Feature Description

In the editor, users can modify the color, background color and text alignment of text elements (titles and paragraphs).

It would be nice to enhance these options by notably letting users style `box-shadow` and `border-radius` of these elements.

### Where to start

Probably the easiest way to start is to have a look at the [<app-align/>](https://github.com/deckgo/deckdeckgo/tree/master/studio/src/app/components/editor/styles/element/app-align) and see how it is implemented and where it is use.

Then a new look a like component for `box-shadow` and another for `border-radius` can be created and integrated.

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

### Mockups

<img width="1054" alt="Capture d’écran 2020-09-05 à 13 35 16" src="https://user-images.githubusercontent.com/16886711/92304282-d236a080-ef7c-11ea-992f-3891bfe239db.png">

For box-shadown probably options as displayed on  https://www.cssmatic.com/box-shadow for example

<img width="1443" alt="Capture d’écran 2020-09-05 à 13 36 26" src="https://user-images.githubusercontent.com/16886711/92304283-d367cd80-ef7c-11ea-957a-7cc1cf1411e5.png">

### Screenshots current options

<img width="1054" alt="Capture d’écran 2020-09-05 à 13 28 22" src="https://user-images.githubusercontent.com/16886711/92304290-e5497080-ef7c-11ea-9547-aa05af4a97ca.png">
<img width="1054" alt="Capture d’écran 2020-09-05 à 13 28 28" src="https://user-images.githubusercontent.com/16886711/92304291-e9758e00-ef7c-11ea-93cb-b6a25bba1d80.png">
<img width="1054" alt="Capture d’écran 2020-09-05 à 13 29 18" src="https://user-images.githubusercontent.com/16886711/92304292-eaa6bb00-ef7c-11ea-8881-e5fc04fad24e.png">

**Comment by thomasledoux1** [comment]
I'd like to pick this up!
