### ISSUE TITLE
kit: prompt user to reload when a new version is available

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#869]
### Affected part of DeckDeckGo
- [X] [Studio kit](https://github.com/deckgo/studio-kit)
 
### Feature Description

The goal of this feature is to detect, with the service worker, when a new version is available and to prompt the user to reload its presentation to get the last update.

### Tech

This feature has to be implemented in the [studio kit](https://github.com/deckgo/studio-kit).

In  this project we are using  Workbox v5. Their  documentation displays an example about how to offer a page reload for users:

https://developers.google.com/web/tools/workbox/guides/advanced-recipes

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by boradakash** [comment]
I would like to take this one up, can you assign me?

**Comment by peterpeterparker** [comment]
Awesome

**Comment by peterpeterparker** [comment]
This has been solved, forgot to close the issue ;)
