### ISSUE TITLE
studio: svg waves for deck or slide background

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#874]
### Affected part of DeckDeckGo
- [X] Studio

### Feature Description

Being able to generate a wave as svg for the background of the deck or slide.

Basically, [https://getwaves.io/](https://getwaves.io/) but integrated into DeckDeckGo.

Currently you can select a background color or an image (custom, gif, unsplash). These are going to be applied to either  deck or slide background. The  idea would be to add a new options to generate a svg wave and apply it for such slot.

### Use Case

It's cool I think.

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

### Screenshot

<img width="1261" alt="Capture d’écran 2020-09-17 à 12 09 17" src="https://user-images.githubusercontent.com/16886711/93456943-a3a2b900-f8de-11ea-9539-63ca180bea75.png">

**Comment by anup-a** [comment]
Shall I work on this ?  would look cool tbh
![image](https://user-images.githubusercontent.com/29516633/94372270-d0926f80-0119-11eb-9bfe-35be2d0162fd.png)

I think a good place to add would be in the image container ....  & something like toggle should work.
Also what all customization buttons are you looking for ?  opacity, color?

**Comment by peterpeterparker** [comment]
@anup-a thx for reaching out!

just to be sure before going further, is the scope feature request clear for you respectively it is not a library we are looking to add, the svg generator itself as to be developed. would that work for you?

basically the example/screenshot I gave above have to be implemented from scatch.

**Comment by anup-a** [comment]
@peterpeterparker definitely looking ahead to work on this 🦄.  I just need some time to look into bezier-spline functions ( and some maths ) ...

**Comment by peterpeterparker** [comment]
Cool  @anup-a ! I assigned you the task.

### SVG Generation

Not sure if it needs bezier-spline and  other complexity. I  found the following example yesterday, maybe it can help?

https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections

Maybe we can even  implement such a generator if easier?

### About the UX

so yes, it is the right place. Not sure if all the options should find  place  in the popover menu or if we  should rather add a button in the menu which opens a modal

maybe there  is more spaces in a modal to put the generator?

**Comment by anup-a** [comment]
I found getwaves.io generator more easier to use .... Intially I'll try to implement something like getwaves.

Q and C you see in svg paths are nothing but bezier quadratic and cubic functions.

**Comment by peterpeterparker** [comment]
Sounds super to me! Keep me posted and if you have questions or need help, ping me anytime.

**Comment by anup-a** [comment]
Something came up. unassigning for now.

**Comment by peterpeterparker** [comment]
No worries, thx for letting me now. Ping me if you would have time again.

**Comment by hjades** [comment]
hi! i'm interested in this~ can i work on this issue?

**Comment by peterpeterparker** [comment]
sure @hjades 👍 

is  the issue and everything which has  to be developed clear or do you have questions?

**Comment by hjades** [comment]
yup! correct me if i'm wrong, these are the things that need to be done:

- [ ]  implement svg wave generator (function)
- [ ] add `SVG Waves (?)` as one of background image option
- [ ] implement svg generator ui (modal)
- [ ] add svg to background slot

**Comment by peterpeterparker** [comment]
exactly @hjades we are on the same page, awesome!

ping me anytime if you have questions,  have fun and thank you for your help 🙏
