### ISSUE TITLE
studio: box-shadow

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#881]
### Affected part of DeckDeckGo
- [X] Studio

### Feature Description

In the editor, users can modify the color, background color and text alignment of text elements (titles and paragraphs).

It would be nice to enhance these options by notably letting users style `box-shadow` of these elements.

### Get Started

This feature request is a split of #865 which contains the description and information to get started.

**Comment by thomasledoux1** [comment]
I'd like to pick this one up!
