### ISSUE TITLE
studio: missing CSS oveflow hidden in list of fonts

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#882]
### Affected part of DeckDeckGo
- [X] Studio

### Actual Behavior

Not yet in production, but in master branch, in the style options of the presentation, the list of fonts displayed in `div` is missing a CSS style `oveflow: hidden`

### Expected Behavior

No ugly overflow 😉.

### Reproduction

Steps to reproduce:

```
git clone  https://github.com/deckgo/deckdeckgo
cd deckdeckgo/studio
npm ci
npm run start
```

create a new presentation and select the style of the deck.

### Screenshot

<img width="1237" alt="Capture d’écran 2020-09-26 à 10 08 04" src="https://user-images.githubusercontent.com/16886711/94336100-b4d77e00-ffe0-11ea-90b1-3a3f8036531d.png">

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by zh-betina** [comment]
@peterpeterparker Hi, I'd like to help but it would be my first-time contribution here on GitHub, I hope I won't mess up anything. 🙂

**Comment by peterpeterparker** [comment]
@zh-betina awesome, thank you for your help 🙏

no worries, you won't mess up anything 😉

if you need any assistance let me know, happy to help.

ps.: note, if you are taking part to hacktoberfest, of course this issue can wait till October

**Comment by zh-betina** [comment]
@peterpeterparker That's right! I'm participating and that's how I found this issue. Thank you so much :) 🙏I'll ping you if I get lost.

**Comment by peterpeterparker** [comment]
sounds like a plan, thx!
