### ISSUE TITLE
studio: letter spacing

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#888]
### Affected part of DeckDeckGo
- [X] Studio
 
### Feature Description

In the editor, users can modify the color, background color etc. of text elements (titles and paragraphs).

We've got two improvements in the making to add [border-radius](https://github.com/deckgo/deckdeckgo/issues/865) and [box-shadow](https://github.com/deckgo/deckdeckgo/issues/881).

It would be maybe nice to enhance these options with `letter-spacing`.

###  How to

```
git clone https://github.com/deckgo/deckdeckgo/
cd deckdeckgo/studio
npm  i
```

Then, you can have  a look and implement the feature in the component [app-align](https://github.com/deckgo/deckdeckgo/tree/master/studio/src/app/components/editor/styles/element/app-align). It can be done in the same way as the `alignment`

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

### Screenshot

<img width="1208" alt="Capture d’écran 2020-09-27 à 10 48 36" src="https://user-images.githubusercontent.com/16886711/94363966-47058200-00c6-11eb-8e9f-51daadcf7997.png">

**Comment by thomasledoux1** [comment]
@peterpeterparker I can pick this one up!

**Comment by peterpeterparker** [comment]
Sure, it  look alike the two other one you are currently making, it matches well!

Thx Thomas
