### ISSUE TITLE
core: auto slide

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#890]
### Affected part of DeckDeckGo
- [X] Web Components
 
### Feature Description

Add an option to swipe slides automatically after x seconds (or milliseconds?).

It means: if the option is set, the presentations with step through the slides without user inputs. 

### Question

Should it always auto-slide or do we want to pause the auto slide on mouse inactivity ?

### Get started

This feature has to be developed in the [core](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/core) Web Component

```
git clone https://github.com/deckgo/deckdeckgo
cd deckdeckgo/webcomponents/core
npm i
npm run start
```

### Property

I guess we can add a new Property `auto-slide` respectively. I would say per default `undefined` aka no auto slide

```
@Prop()
autoSlide: number | undefined;
```

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by kala2** [comment]
Hello,

Is this available? Can i take it?

**Comment by peterpeterparker** [comment]
Sure @kala2 go for it! Thx 🙏

Let me know if you have questions!

**Comment by peterpeterparker** [comment]
I would be happy to send you some DeckDeckGo stickers @kala2.
If interested, send me your address in a pm.
