### ISSUE TITLE
docs: auto slide

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#893]
### Documentation

An "auto slide" feature has been recently developed (#890). It is now possible to set a presentation to swipe slides automatically after X seconds (5000 milliseconds per default).

This feature request aims to add this new option to the documentation for developers.

### Properties

This new options comes with two new properties which can be optionally  set on the deck (`<deckgo-deck/>`) level.

| prop  | attribute  | type  |  default |
|---|---|---|---|
|  autoSlide |  auto-slide | boolean  | false  | 
| autoSlideInterval  | auto-slide-interval   |  number | 5000  |

### Page

This new option is not yet documented and therefore needs a new dedicated page in the docs.

https://docs.deckdeckgo.com/deck/auto-slide

### What do  do

To add a new page, the [animation](https://docs.deckdeckgo.com/deck/animation) documentation example can be followed.

1. Add a new TSX component `app-auto-slide` (see [app-animation](https://github.com/deckgo/deckdeckgo/tree/master/docs/src/app/pages/docs/deck/app-deck-animation) source  as example). The `render` content does not matter as it will be parsed at build time aka will be overwrite  later with the related markdown file.

2. Add a new route in [app-root](https://github.com/deckgo/deckdeckgo/blob/master/docs/src/app/app-root.tsx)

3. Create the documentation in markdown. The [animation](https://github.com/deckgo/deckdeckgo/blob/master/docs/docs/deck/app-deck-animation/app-deck-animation.md) example can be followed.

Note that there is no live reload to parse the mardkow to JSX.

###  Start

```
git clone https://github.com/deckgo/deckdeckgo
cd deckdeckgo/docs
npm i
npm run start
```

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by HugoLiconV** [comment]
I'll be working on this

**Comment by peterpeterparker** [comment]
super thx @HugoLiconV !
