### ISSUE TITLE
new component: markdow parser

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#900]
### Affected part of DeckDeckGo
- [X] Web Components
 
### Feature Description

I was thinking it would be cool to be able to use Markdown in our editor. Currently users can create slides in which they add title, paragraphs, images, code and math. Markdown would be a new type of section.

In such section, users would be able to use Markdown and when the section is blurrred, then  HTML would be rendered.

### Technical solution

The component should expose a `<slot/>` and if something is passed,  transform the content from markdow to HTML.

It can/should work the same way as the [highlight-code](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/highlight-code) or [math](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/math) component.

Math component being a bit lighter, I suggest to have a  look at this to begin.

For the conversion to markdown to html I think that [remarkable](https://github.com/jonschlinkert/remarkable) or [slowdown](https://github.com/showdownjs/showdown) can be use, but, according Bundleophobia, remarkable is lighter so maybe it is better to use that library.

### Steps

In a first step, this feature has for goal to create a new standalone component.

Later on, we can then integrate it to our starter kits and editor ("studio"), but first, the component is the goal.

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by Christiak** [comment]
@peterpeterparker Hello, Can I try to work on this component ?? 😀

**Comment by peterpeterparker** [comment]
sure go for  it @Christiak !!! If you need any help, let me know 😃
