### ISSUE TITLE
studio: full screen editor options minimized per default

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#901]
### Affected part of DeckDeckGo
- [X] Studio
 
### Feature Description

One particularity of our editor is that it remains editable in full screen mode as it would be if windowed or on mobile devices. Likewise, all options are  available in full screen.

Even though I really love that function, it bugs me that when people are presenting the tools are displayed.

That's why I thought it would be cool to keep the editable feature but to find a way to not display automatically the tool panel. 

That's why I came to the idea to displaying the tool per default, minimized in full screen or in other word, per default the full screen mode is not editable but there is a toggle displayed somewhere which allow the users to switch quickly to edit mode while remaining in full screen.

I don't know exactly how it should be designed and I am open to any suggestions.

### Use Case

When people are presenting, they don't want to edit but probably show  something with their mouse, it's a like a normal behavior / reflex I  noticed while seeing people presenting with or without DeckDeckGo.

### Screenshots

(a presentation in full screen)

![Capture d’écran 2020-10-01 à 21 00 19](https://user-images.githubusercontent.com/16886711/94852011-8c5ce300-0429-11eb-83a5-7e779841f4ea.png)

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by andreas0607** [comment]
I'll have a go at this👍

**Comment by peterpeterparker** [comment]
that would be cool @andreas0607 ! thx

**Comment by andreas0607** [comment]
@peterpeterparker I have made a PR for partly fixing this issue. 
I have not done anything regards to border-sections.
I'll see what I can do about that at another time✌️

**Comment by peterpeterparker** [comment]
Awesome @andreas0607 👍 I'll check it this evening and will try afterwards to see if I can do the border thing

**Comment by peterpeterparker** [comment]
I just reopen it and assign  myself the issue as I still want to check the `border-radius` thing, but the rest, respectively  the PR provided by @andreas0607 is super.

**Comment by andreas0607** [comment]
That's really awesome! I'll make sure to check it out😍

**Comment by peterpeterparker** [comment]
Thanks Andreas, happy to hear that 🙏

I reused (copy/paste) a bottom sheet component I developed to present the notes in our remote control. I did not extract it as a standalone component because in the future (soon I hope), Ionic will unleash a bottom sheet component. I'll then be able to remove my custom code 😉.
