### ISSUE TITLE
studio: save used colors

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#902]
### Affected part of DeckDeckGo
- [X] Studio
 
### Feature Description

In our editor, we are using several times our color picker (`<deckgo-color/>`). I think, instead of  always using  the default palette, it would  be cool to use a palette which keeps track  of the color used by the user.

We can initialize the palette with the default and if for example the user is selecting red or a custom weird color, this color becomes the first one in the list,  the first one displayed  in the color picker. Therefore, every time the user access the color picker, he/she finds the color he/she has used recently.

###  Get Started

The enhancement has  to be developed  in our editor, studio

```
git clone https://github.com/deckgo/deckdeckgo
cd deckdeckgo/studio
npm i
npm run start
```

### Development

Spontaneously I think that these are the steps

1. Create a new [store](https://github.com/deckgo/deckdeckgo/tree/master/studio/src/app/stores) / state management for that color 

2. Register an action `onChange` which save the value of the palette in IDB each time  the palette  change

3. When the app starts, the state should be initialized in [app-root](https://github.com/deckgo/deckdeckgo/blob/master/studio/src/app/app-root.tsx) from its valud in IDB. If none found, use the default palette (the code can be copied [there](https://github.com/deckgo/deckdeckgo/blob/97b8c4b2deb2b51358aead422aeee18b2c75a065/webcomponents/color/src/utils/deckdeckgo-palette.ts#L17)

4. For each `<deckgo-color/>` add the property `palette` assigned with the store value

5. For each of  these `<deckgo-color/>` find their change property and each time a color is selected, update the  store accordingly 

### Screenshot

<img width="1196" alt="Capture d’écran 2020-10-01 à 21 21 40" src="https://user-images.githubusercontent.com/16886711/94853831-40f80400-042c-11eb-9557-77d4140b57a4.png">

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by andreas0607** [comment]
I'd like to contribute by working on this issue👋

**Comment by peterpeterparker** [comment]
That would be awesome @andreas0607 ! it's an idea I had recently because it bugs me when I edit presentation, so moreover than improving the product it would make me happier when I create my desck 😃

Ping me if you have any ideas or need help!
