### ISSUE TITLE
studio: add default 'each corner' for border radius

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#908]
### Affected part of DeckDeckGo
- [x] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

 
### Feature Description

Introduced in #894, the studio now provides border radius set on the background, where you can set each corner individually. 

![image](https://user-images.githubusercontent.com/1763537/94899500-bcd96700-0493-11eb-82f3-3cd726f53f1c.png)

To generate less noise, this could be improved to create a better user experience. 

Create a dropdown that has two values:
* Each corner
* Individual corner

[ Each corner ⊻ ] 

----⚫️----------------   [ 5 ]

Then when you swap the dropdown value to 'individual corner', the current implementation will be shown.

### Use Case

I think 90% will use the 'default' border radius set for all corners, so you don't need this extra noise to create a better experience for the user.

**Comment by peterpeterparker** [comment]
@thomasledoux1 should I assign you the task I did understood correctly?

if not of course no problem, just a question ;)

**Comment by thomasledoux1** [comment]
@peterpeterparker yes, you can assign it to me!

**Comment by peterpeterparker** [comment]
awesome 👍
