### ISSUE TITLE
refactor: add optional chaining in code

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#920]
### Affected part of DeckDeckGo
- [x] All
 
### Feature Description

Since TypeScript 3.7, optional chaining can be used to get rid of redundant code.

Example:

```ts
this.foo && this.foo.bar && this.foo.bar.foobar
```

can be simplified to

```ts
this.foo.bar?.foobar
```

See [release notes of TypeScript 3.7 for more information](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining).

**Only easy to rewrite things will be touched first.**

### Use Case

It will make the code more robust with less errors. The studio is the most important part to do this. That will be the first 'mover'.

**Comment by peterpeterparker** [comment]
Also linked https://github.com/deckgo/deckdeckgo/pull/937

**Comment by peterpeterparker** [comment]
Yes thanks for the feature  and many PRs @donroyco  👍
