### ISSUE TITLE
bug(a11y): color picker does not show focus state

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#922]
### Affected part of DeckDeckGo

- [x] Components

The [color picker](https://docs.deckdeckgo.com/components/color/) is affected.

### Reproduction

Steps to reproduce:

1. Go to https://docs.deckdeckgo.com/components/color/ or write a presentation and select _Style_.
2. Use <kbd>Tab</kbd> to navigate through content until you're at the color palette.

### Expected Behavior

To see the color have an outline like it would have being the selected color.

### Actual Behavior

The colors do not have an outline, only until they are selected (with <kbd>Spacebar</kbd>).

![Oct-06-2020 20-04-21](https://user-images.githubusercontent.com/1763537/95242227-2ef0d980-080f-11eb-9389-368f358c6368.gif)
_Current behaviour in color picker._

### Environment
Latest Chrome on macOS

**Comment by ITSjwags** [comment]
Threw in a quick PR to help with this bug. Let me know if I'm missing something here or you want anything else changed/added.

**Comment by peterpeterparker** [comment]
I'll review the PR asap @ITSjwags. Thx a lot for your help 🙏.
