### ISSUE TITLE
studio: improve poll UX to support multiple polls within the same presentation

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#942]
### Affected part of DeckDeckGo

- [X] Studio

### Feature Description

In addition to the editor, "studio" also contains a feature which let attendees vote for a [poll](https://deckdeckgo.com/poll/).

In order to let your attendees vote multiple times for the same poll, the poll key is saved in indexedb and a user can't vote  for the same key for two hours.

This works fine but I noticed two things which should be improved in terms of UX, specially if the presenter has included multiple polls in his/her presentation:

1. Once the user has voted, results and data are kept in memory and therefore he/she finds him/herself blocked and can't vote for another poll, therefore this feature should add a `button` or `link` on the result screen (see screenshot) which should reset the poll  (this can be done by calling the function `cancel()` in [app-poll](https://github.com/deckgo/deckdeckgo/blob/master/studio/src/app/pages/core/app-poll/app-poll.tsx)

2. Likewise, when use navigate elsewhere in the application (when the app change route), the `cancel()` function should be called  too. Note that moreover than `disconnectcallback` you may have to observe the route  change too. You can have a look at [app-editor](https://github.com/deckgo/deckdeckgo/blob/b64ac37913457e7ffe4676024bd498580b370541/studio/src/app/pages/editor/app-editor/app-editor.tsx#L116)  for an example.

### Use Case

Allow attendees to vote for multiple polls without the need to refresh their apps. 

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

### Screenshot

<img width="834" alt="Capture d’écran 2020-10-09 à 09 43 37" src="https://user-images.githubusercontent.com/16886711/95557470-28cc4a00-0a15-11eb-85b1-ca570d098837.png">

**Comment by yighax** [comment]
Hi. I would like to work on this issue.

**Comment by peterpeterparker** [comment]
Awesome @yighax that's an important improvement, go for it 👍

**Comment by peterpeterparker** [comment]
@yighax may I ask you if you are working on this one? it's an important one, if you would have not time to solve it let me know. Thanks in advance for your feedback.

**Comment by yighax** [comment]
Yes, i had some other tasks i needed to finish, but now i am fully committed to this issue.

**Comment by peterpeterparker** [comment]
super! ping me if you need any help

**Comment by peterpeterparker** [comment]
Please accept my apologies @yighax but this had become a really important issue and I had to find a solution to roll it out as soon as possible for our users as it was requested.

Hope you will understand.
