### ISSUE TITLE
docs: new component "word cloud"

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#951]
### Documentation

A new component [word cloud](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/word-cloud) has been developed and published.

The goal of this issue is to document it in our [documentation](docs.deckdeckgo.com/) for developers.

### Route

This component is not yet documented therefore, it should be in a new route:

https://docs.deckdeckgo.com/components/word-cloud

### What do  do

To add a new page, the [math](https://docs.deckdeckgo.com/components/math) example can be followed.

1. Add a new TSX component `app-word-cloud` (see [app-math](https://github.com/deckgo/deckdeckgo/tree/master/docs/src/app/pages/docs/components/app-components-math) source  as example). The `render` content does not matter as it will be parsed at build time aka will be overwrite  later with the related markdown file.

2. Add a new route in [app-root](https://github.com/deckgo/deckdeckgo/blob/master/docs/src/app/app-root.tsx)

3. Create the documentation in markdown. The [math](https://github.com/deckgo/deckdeckgo/blob/master/docs/docs/components/app-components-math/app-components-math.md) example can be followed.

Note that there is no live reload to parse the markdown to JSX. Restart `npm run start` to populate the changes.

###  Get starter

```
git clone https://github.com/deckgo/deckdeckgo
cd deckdeckgo/docs
npm i
npm run start
```

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by achimoraites** [comment]
Hello @peterpeterparker !
Can I take it ?

**Comment by peterpeterparker** [comment]
sure of course, go for it! thx 🙏
