### ISSUE TITLE
Webpack Exception

### ISSUE THREAD

**Issue by tarakeshp** [deckgo/deckdeckgo#955]
When I tried to 
npm run start or
npm run local
I am facing the below issue.

Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html

**Comment by peterpeterparker** [comment]
@tarakeshp with which project? our starter kit or another app?

**Comment by tarakeshp** [comment]
> @tarakeshp with which project? our starter kit or another app?

**Comment by tarakeshp** [comment]
https://docs.deckdeckgo.com/docs/ - following the instructions

**Comment by peterpeterparker** [comment]
Worked out for me

>     [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 16.1 KiB {HtmlWebpackPlugin_0} [built]
> ℹ ｢wdm｣: Compiled successfully.

You are on windows? what's your node and npm versions?

**Comment by tarakeshp** [comment]
Mac - Version - Catalina 10.15.7
Node - Version - v12.18.4

the starter kit (https://github.com/deckgo/starter-kit) works though but the not the above one. I would like to use it as a editor version. Simple drag and drop components

**Comment by peterpeterparker** [comment]
Weird I've got  a Mac too and I was  guessing that Node v12 was ok.

Can you provide me the repo you can't compile?

**Comment by tarakeshp** [comment]
I have re-installed the following plugin 
deckdeckgo-webpack-plugins - it works now. Its weird.

Shall I ask you for a suggestion ? is there any editor where I can drag and drop components instead of writing. 
Just like slides.com, paperbits.com

**Comment by peterpeterparker** [comment]
glad to hear it worked out.

no idea what you mean with "drag and drop components", which components?

**Comment by tarakeshp** [comment]
https://demo.paperbits.io/
https://slides.com/
Have a look at these. 
1. you choose a layout.
2. Align the components such as text, images, video etc
3. publish them as json or md file
4. each slide becomes a perma link.

**Comment by peterpeterparker** [comment]
yes looks good, these are cool editors

**Comment by tarakeshp** [comment]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:9000] (webpack)-dev-server/client?http://localhost:9000 4.29 KiB {main} [built]
[./src/index.js] 5.51 KiB {main} [built]
    + 434 hidden modules
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 6.79 KiB {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Compiled successfully.
[Error: ENOENT: no such file or directory, open './dist/index.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './dist/index.html'
}

why do I see this error though the build works.

**Comment by tarakeshp** [comment]
deckdeckgo has any such editors ?

**Comment by peterpeterparker** [comment]
https://deckdeckgo.com

for the error, plz provide a sample repo to reproduce the error
