### ISSUE TITLE
social: medium has changed their profile urls

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#959]
### Affected part of DeckDeckGo

- [X] Web Components

### Feature Description

The [social](https://docs.deckdeckgo.com/components/social/) web component is used in the template author to automatically parse logo and more important link to social url.

For example if used as following, a link to twitter with the correct url format `https://twitter.com/daviddalbusco` will be rendered.

```
<deckgo-social twitter="daviddalbusco">
  <ion-icon slot="icon" name="logo-twitter"></ion-icon>
</deckgo-social>
```

This works  like  a charm. Now, I just noticed that Medium did change the user's  profile url.

Was: `https://medium.com/@david.dalbusco`

New: `https://daviddalbusco.medium.com/`

The goal of this feature  is therefore to update the Medium URL in the [Social component](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/social) source code.

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

**Comment by sai-github** [comment]
Can I take this ?

**Comment by peterpeterparker** [comment]
Sure awesome! Got for it 👍
