### ISSUE TITLE
studio: display slide number in breadcrumbs 

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#966]
### Affected part of DeckDeckGo

- [X] Studio

### Feature Description

This feature as for goal to display the current active slide number in the breadcrumbs of the editor.

For example, instead of displaying `Deck > Slide > Element` it should display `Deck > Slide #19 > Element`.

### Technical Info

The `#` as `<small>#</small>`.

The number, the slide index, is dynamic. It can be retrieved on the `<deckgo-deck>` with the method `getActiveIndex(): Promise<number>`.

### Where to start

The component to update is the following: https://github.com/deckgo/deckdeckgo/tree/master/studio/src/app/components/editor/actions/app-breadcrumbs

To start locally the editor:

```
git clone https://github.com/deckgo/deckdeckgo
cd deckdeckgo/studio
npm i
npm run start
```

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

### Screenshot

<img width="961" alt="Capture d’écran 2020-10-18 à 15 13 26" src="https://user-images.githubusercontent.com/16886711/96368651-4d32cf80-1155-11eb-876f-f7ae8e45a160.png">

**Comment by RodolfoNei** [comment]
Hello! Can I work on this issue, please?

**Comment by peterpeterparker** [comment]
Sure thx @RodolfoNei ! Let me know if you have any questions and thx for your help.

**Comment by peterpeterparker** [comment]
P.S.: @RodolfoNei I just added a new section "Where to start" to the description of the feature, hope  it helps to get started

**Comment by RodolfoNei** [comment]
Alright @peterpeterparker! Thank you.

**Comment by RodolfoNei** [comment]
Hello @peterpeterparker. I have been struggling a little bit with this one. I'm a complete beginner with TypeScript and JS in general, so I just started tweaking the code and trying to figure out the issue. I managed to insert the markup of the # and the placeholder to the slide number, that refers to a Prop() I am currently hard-coding the numbers being displayed:
```
@Prop()
  slidenum: number = 1;
```

And inside the button:
```
<ion-label>{step} {step === 'slide' ? <span><small>#</small>{this.slidenum}</span> : null}</ion-label>
// Slide #1
```
But now I'm having problems to get the actual slide number. I'm trying with the getActiveIndex() but all the examples I see from it in the code are inside other async functions, and I am not figuring out how to translate it to a Prop() definition.  Is this the right way to go or there are better ones?

**Comment by peterpeterparker** [comment]
@RodolfoNei cool to hear you made some progress and thx for reaching out 👍

there are a couple of solutions I think.

a first one I can think of is using a `State()` instead of a `Prop()` for the index and adding a `@Watch()` on `step` to recalculate the index each time step  is set

```
@State()
private slidenum: @number;

@Watch('step')
async onStepChange() {
     const deck = document.querySelector('main > deckgo-deck');

      if (!deck) {
        return;
      }

    this.slidenum = await deck.getActiveIndex();
}
```

but not sure if that would work, I think it can because step is often set but not sure it is performant.

another solution, would be to transform the `index` in `onSlideChange` of `app-editor` to a `@State()`  too and then path the state  to  a new `@Prop` to `app-actions-editor`  which would  then pass this new property to `app-breadcrumbs`.

It would be  a bit more performant I think but then a value has to  be path through to components.

Does that help? What do you think? Let me me know, happy to help.
