### ISSUE TITLE
wrong position of the "play" button in the remote

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#991]
### Affected part of DeckDeckGo

- [X] Remote control

### Reproduction

Steps to reproduce:

1. Open the remote: https://deckdeckgo.app
2. Open the demo: https://demo.deckdeckgo.com
3. Connect the remote with this presentation
4. Go to the slide "Youtube"

### Behavior

In the [remote control](https://deckdeckgo.app) a "Play / Pause" button is displayed if the current slide contains a video, such as a "Youtube" slide. This button was and should be displayed centered between the two "Previous / Next slide" buttons. 

This isn't the case anymore.

The goal of this issue is to set this correct position for such button.

### Code

This issue as to be implemented in the remote control:

```
git clone https://github.com/deckgo/deckdeckgo
cd deckdeckgo/remote
npm i
npm run start
```

### Screenshots

<img width="1167" alt="Capture d’écran 2020-11-01 à 19 36 26" src="https://user-images.githubusercontent.com/16886711/97811336-41c5c500-1c7a-11eb-8cba-4d6d175509e3.png">
<img width="752" alt="Capture d’écran 2020-11-01 à 19 36 37" src="https://user-images.githubusercontent.com/16886711/97811340-438f8880-1c7a-11eb-848e-bc3b93f45bd7.png">

**Comment by MehulG** [comment]
Hi peter! I would like to resolve this issue. As this would be my first open source contribution, I hope you would bear with me.

**Comment by peterpeterparker** [comment]
Sure go for it @MehulG, thx 👍

**Comment by MehulG** [comment]
@peterpeterparker I changed local CSS and I think issue is fixed now. I have raised a pull request

**Comment by peterpeterparker** [comment]
Awesome @MehulG 💪 I will try to have a look asap!
